// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace MioGame;

public static class MioGameModule {
    public static ulong MioGameFunctionAddress => MioGameMemoryAddress + _functionOffset;
    
    public static ulong MioGameMemoryAddress {
        get => _address != 0 ? _address : throw new InvalidOperationException("Must set field before reading");
        set => _address = value;
    }
    
    private static ulong _address;
    private static readonly ulong _functionOffset = 4096;
}
