// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame;

/// Struct type: __m128<br/>TypeIndex: 168300 (0x2A16C)<br/>UniqueName: .?AT__m128@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct __m128 {
    #region Instance Fields
    /// Field: CsArray float<br/>TypeIndex: 7474 (0x2D32)
    [FieldOffset(0)] public global::MioGame.InlineArray_float_4 m128_f32;
    /// Field: CsArray ulong<br/>TypeIndex: 805 (0x1325)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt64Quad_2 m128_u64;
    /// Field: CsArray sbyte<br/>TypeIndex: 3430 (0x1D66)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_16 m128_i8;
    /// Field: CsArray short<br/>TypeIndex: 148048 (0x25250)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt16Short_8 m128_i16;
    /// Field: CsArray int<br/>TypeIndex: 5216 (0x2460)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt32_4 m128_i32;
    /// Field: CsArray long<br/>TypeIndex: 111692 (0x1C44C)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt64Quad_2 m128_i64;
    /// Field: CsArray byte<br/>TypeIndex: 1783 (0x16F7)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUnsignedChar_16 m128_u8;
    /// Field: CsArray ushort<br/>TypeIndex: 148051 (0x25253)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_8 m128_u16;
    /// Field: CsArray uint<br/>TypeIndex: 3427 (0x1D63)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt32_4 m128_u32;
    #endregion
}
/// Struct type: __m128i<br/>TypeIndex: 148059 (0x2525B)<br/>UniqueName: .?AT__m128i@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct __m128i {
    #region Instance Fields
    /// Field: CsArray sbyte<br/>TypeIndex: 3430 (0x1D66)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_16 m128i_i8;
    /// Field: CsArray short<br/>TypeIndex: 148048 (0x25250)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt16Short_8 m128i_i16;
    /// Field: CsArray int<br/>TypeIndex: 5216 (0x2460)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt32_4 m128i_i32;
    /// Field: CsArray long<br/>TypeIndex: 111692 (0x1C44C)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt64Quad_2 m128i_i64;
    /// Field: CsArray byte<br/>TypeIndex: 1783 (0x16F7)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUnsignedChar_16 m128i_u8;
    /// Field: CsArray ushort<br/>TypeIndex: 148051 (0x25253)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_8 m128i_u16;
    /// Field: CsArray uint<br/>TypeIndex: 3427 (0x1D63)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt32_4 m128i_u32;
    /// Field: CsArray ulong<br/>TypeIndex: 805 (0x1325)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt64Quad_2 m128i_u64;
    #endregion
}
/// Struct type: __m256<br/>TypeIndex: 168508 (0x2A23C)<br/>UniqueName: .?AT__m256@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct __m256 {
    #region Instance Fields
    /// Field: CsArray float<br/>TypeIndex: 11145 (0x3B89)
    [FieldOffset(0)] public global::MioGame.InlineArray_float_8 m256_f32;
    #endregion
}
/// Struct type: __m256i<br/>TypeIndex: 148094 (0x2527E)<br/>UniqueName: .?AT__m256i@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct __m256i {
    #region Instance Fields
    /// Field: CsArray sbyte<br/>TypeIndex: 1786 (0x16FA)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_32 m256i_i8;
    /// Field: CsArray short<br/>TypeIndex: 148080 (0x25270)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt16Short_16 m256i_i16;
    /// Field: CsArray int<br/>TypeIndex: 127998 (0x203FE)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt32_8 m256i_i32;
    /// Field: CsArray long<br/>TypeIndex: 148086 (0x25276)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt64Quad_4 m256i_i64;
    /// Field: CsArray byte<br/>TypeIndex: 5875 (0x26F3)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUnsignedChar_32 m256i_u8;
    /// Field: CsArray ushort<br/>TypeIndex: 148089 (0x25279)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_16 m256i_u16;
    /// Field: CsArray uint<br/>TypeIndex: 10654 (0x399E)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt32_8 m256i_u32;
    /// Field: CsArray ulong<br/>TypeIndex: 1837 (0x172D)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt64Quad_4 m256i_u64;
    #endregion
}
/// Struct type: __m512<br/>TypeIndex: 190354 (0x2F792)<br/>UniqueName: .?AT__m512@@
[StructLayout(LayoutKind.Explicit, Size = 64)]
public partial struct __m512 {
    #region Instance Fields
    /// Field: CsArray float<br/>TypeIndex: 1094 (0x1446)
    [FieldOffset(0)] public global::MioGame.InlineArray_float_16 m512_f32;
    #endregion
}
/// Struct type: __m512i<br/>TypeIndex: 189253 (0x2F345)<br/>UniqueName: .?AT__m512i@@
[StructLayout(LayoutKind.Explicit, Size = 64)]
public partial struct __m512i {
    #region Instance Fields
    /// Field: CsArray sbyte<br/>TypeIndex: 1872 (0x1750)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_64 m512i_i8;
    /// Field: CsArray short<br/>TypeIndex: 112330 (0x1C6CA)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt16Short_32 m512i_i16;
    /// Field: CsArray int<br/>TypeIndex: 189245 (0x2F33D)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt32_16 m512i_i32;
    /// Field: CsArray long<br/>TypeIndex: 189247 (0x2F33F)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt64Quad_8 m512i_i64;
    /// Field: CsArray byte<br/>TypeIndex: 3425 (0x1D61)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUnsignedChar_64 m512i_u8;
    /// Field: CsArray ushort<br/>TypeIndex: 189249 (0x2F341)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_32 m512i_u16;
    /// Field: CsArray uint<br/>TypeIndex: 1393 (0x1571)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt32_16 m512i_u32;
    /// Field: CsArray ulong<br/>TypeIndex: 1561 (0x1619)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt64Quad_8 m512i_u64;
    #endregion
}
/// Struct type: __m64<br/>TypeIndex: 190329 (0x2F779)<br/>UniqueName: .?AT__m64@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct __m64 {
    #region Instance Fields
    /// Field: unsigned __int64 (UInt64Quad | Direct)
    [FieldOffset(0)] public CppUInt64Quad m64_u64;
    /// Field: CsArray float<br/>TypeIndex: 6808 (0x2A98)
    [FieldOffset(0)] public global::MioGame.InlineArray_float_2 m64_f32;
    /// Field: CsArray sbyte<br/>TypeIndex: 1032 (0x1408)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_8 m64_i8;
    /// Field: CsArray short<br/>TypeIndex: 190324 (0x2F774)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt16Short_4 m64_i16;
    /// Field: CsArray int<br/>TypeIndex: 46782 (0xC6BE)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt32_2 m64_i32;
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad m64_i64;
    /// Field: CsArray byte<br/>TypeIndex: 1244 (0x14DC)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUnsignedChar_8 m64_u8;
    /// Field: CsArray ushort<br/>TypeIndex: 106206 (0x1AEDE)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_4 m64_u16;
    /// Field: CsArray uint<br/>TypeIndex: 3489 (0x1DA1)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt32_2 m64_u32;
    #endregion
}
/// Struct type: _Dconst<br/>TypeIndex: 189219 (0x2F323)<br/>UniqueName: .?AT_Dconst@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct _Dconst {
    #region Instance Fields
    /// Field: CsArray ushort<br/>TypeIndex: 148051 (0x25253)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_8 _Word;
    /// Field: float (Float32 | Direct)
    [FieldOffset(0)] public float _Float;
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _Double;
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _Long_double;
    #endregion
}
/// Struct type: _double_val<br/>TypeIndex: 189197 (0x2F30D)<br/>UniqueName: .?AT_double_val@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _double_val {
    #region Instance Fields
    /// Field: CsArray ushort<br/>TypeIndex: 106206 (0x1AEDE)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_4 _Sh;
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _Val;
    #endregion
}
/// Struct type: _float_const<br/>TypeIndex: 189212 (0x2F31C)<br/>UniqueName: .?AT_float_const@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _float_const {
    #region Instance Fields
    /// Field: CsArray ushort<br/>TypeIndex: 106206 (0x1AEDE)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_4 _Word;
    /// Field: float (Float32 | Direct)
    [FieldOffset(0)] public float _Float;
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _Double;
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _Long_double;
    #endregion
}
/// Struct type: _float_val<br/>TypeIndex: 189207 (0x2F317)<br/>UniqueName: .?AT_float_val@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct _float_val {
    #region Instance Fields
    /// Field: CsArray ushort<br/>TypeIndex: 135030 (0x21F76)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_2 _Sh;
    /// Field: float (Float32 | Direct)
    [FieldOffset(0)] public float _Val;
    #endregion
}
/// Struct type: _hb_var_int_t<br/>TypeIndex: 135035 (0x21F7B)<br/>UniqueName: .?AT_hb_var_int_t@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct _hb_var_int_t {
    #region Instance Fields
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(0)] public CppUInt32 u32;
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 i32;
    /// Field: CsArray ushort<br/>TypeIndex: 135030 (0x21F76)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_2 u16;
    /// Field: CsArray short<br/>TypeIndex: 135032 (0x21F78)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppInt16Short_2 i16;
    /// Field: CsArray byte<br/>TypeIndex: 46401 (0xC541)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUnsignedChar_4 u8;
    /// Field: CsArray sbyte<br/>TypeIndex: 135033 (0x21F79)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppSignedChar_4 i8;
    #endregion
}
/// Struct type: _LARGE_INTEGER<br/>TypeIndex: 1921 (0x1781)<br/>UniqueName: .?AT_LARGE_INTEGER@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _LARGE_INTEGER {
    #region Instance Fields
    /// Field: unsigned long (UInt32Long | Direct)
    [FieldOffset(0)] public CppUInt32Long LowPart;
    /// Field: long (Int32Long | Direct)
    [FieldOffset(4)] public CppInt32Long HighPart;
    /// Field: CsStruct _LARGE_INTEGER__&lt;unnamed-type-u&gt;<br/>TypeIndex: 1941 (0x1795)
    [FieldOffset(0)] public global::MioGame._LARGE_INTEGER.U u;
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad QuadPart;
    #endregion
    #region Nested Types
    /// Struct type: _LARGE_INTEGER::&lt;unnamed-type-u&gt;<br/>TypeIndex: 1941 (0x1795)<br/>UniqueName: .?AU&lt;unnamed-type-u&gt;@_LARGE_INTEGER@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public partial struct U {
        #region Instance Fields
        /// Field: unsigned long (UInt32Long | Direct)
        [FieldOffset(0)] public CppUInt32Long LowPart;
        /// Field: long (Int32Long | Direct)
        [FieldOffset(4)] public CppInt32Long HighPart;
        #endregion
    }
    #endregion
}
/// Struct type: _ldouble_val<br/>TypeIndex: 189020 (0x2F25C)<br/>UniqueName: .?AT_ldouble_val@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _ldouble_val {
    #region Instance Fields
    /// Field: CsArray ushort<br/>TypeIndex: 106206 (0x1AEDE)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppUInt16Short_4 _Sh;
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _Val;
    #endregion
}
/// Struct type: _RTL_RUN_ONCE<br/>TypeIndex: 155561 (0x26FA9)<br/>UniqueName: .?AT_RTL_RUN_ONCE@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct _RTL_RUN_ONCE {
    #region Instance Fields
    /// Field: void* (Void | NearPointer64)
    [FieldOffset(0)] public void* Ptr;
    #endregion
}
/// Struct type: _SLIST_HEADER<br/>TypeIndex: 150724 (0x25CC4)<br/>UniqueName: .?AT_SLIST_HEADER@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct _SLIST_HEADER {
    #region Instance Fields
    /// Field: unsigned __int64 (UInt64Quad | Direct)
    [FieldOffset(0)] public CppUInt64Quad Alignment;
    /// Field: unsigned __int64 (UInt64Quad | Direct)
    [FieldOffset(8)] public CppUInt64Quad Region;
    /// Field: CsStruct _SLIST_HEADER__&lt;unnamed-type-HeaderX64&gt;<br/>TypeIndex: 150765 (0x25CED)
    [FieldOffset(0)] public global::MioGame._SLIST_HEADER.HeaderX64 headerX64;
    #endregion
    #region Nested Types
    /// Struct type: _SLIST_HEADER::&lt;unnamed-type-HeaderX64&gt;<br/>TypeIndex: 150765 (0x25CED)<br/>UniqueName: .?AU&lt;unnamed-type-HeaderX64&gt;@_SLIST_HEADER@@
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public partial struct HeaderX64 {
        #region Instance Fields
        /// Field: unsigned __int64 (UInt64Quad | Direct)
        [FieldOffset(0)] public CppUInt64Quad Depth;
        /// Field: unsigned __int64 (UInt64Quad | Direct)
        [FieldOffset(0)] public CppUInt64Quad Sequence;
        /// Field: unsigned __int64 (UInt64Quad | Direct)
        [FieldOffset(8)] public CppUInt64Quad Reserved;
        /// Field: unsigned __int64 (UInt64Quad | Direct)
        [FieldOffset(8)] public CppUInt64Quad NextEntry;
        #endregion
    }
    #endregion
}
/// Struct type: _UNWIND_CODE<br/>TypeIndex: 149981 (0x259DD)<br/>UniqueName: .?AT_UNWIND_CODE@@
[StructLayout(LayoutKind.Explicit, Size = 2)]
public partial struct _UNWIND_CODE {
    #region Instance Fields
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(0)] public CppUnsignedChar CodeOffset;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(1)] public CppUnsignedChar UnwindOp;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(1)] public CppUnsignedChar OpInfo;
    /// Field: unsigned short (UInt16Short | Direct)
    [FieldOffset(0)] public CppUInt16Short FrameOffset;
    #endregion
}
/// Struct type: FT<br/>TypeIndex: 155777 (0x27081)<br/>UniqueName: .?ATFT@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct FT {
    #region Instance Fields
    /// Field: unsigned __int64 (UInt64Quad | Direct)
    [FieldOffset(0)] public CppUInt64Quad ft_scalar;
    /// Field: CsStruct _FILETIME<br/>TypeIndex: 7479 (0x2D37)
    [FieldOffset(0)] public global::MioGame._FILETIME ft_struct;
    #endregion
}
/// Struct type: hb_options_union_t<br/>TypeIndex: 230189 (0x3932D)<br/>UniqueName: .?AThb_options_union_t@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct hb_options_union_t {
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 i;
    /// Field: CsStruct hb_options_t<br/>TypeIndex: 230194 (0x39332)
    [FieldOffset(0)] public global::MioGame.hb_options_t opts;
    #endregion
}
/// Struct type: LZ4_stream_u<br/>TypeIndex: 110652 (0x1C03C)<br/>UniqueName: 
[StructLayout(LayoutKind.Explicit, Size = 16416)]
public partial struct LZ4_stream_u {
    #region Instance Fields
    /// Field: CsArray sbyte<br/>TypeIndex: 110647 (0x1C037)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_16416 minStateSize;
    /// Field: CsStruct LZ4_stream_t_internal<br/>TypeIndex: 110659 (0x1C043)
    [FieldOffset(0)] public global::MioGame.LZ4_stream_t_internal internal_donotuse;
    #endregion
}
/// Struct type: LZ4_streamDecode_u<br/>TypeIndex: 110681 (0x1C059)<br/>UniqueName: 
[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct LZ4_streamDecode_u {
    #region Instance Fields
    /// Field: CsArray sbyte<br/>TypeIndex: 1786 (0x16FA)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_32 minStateSize;
    /// Field: CsStruct LZ4_streamDecode_t_internal<br/>TypeIndex: 110684 (0x1C05C)
    [FieldOffset(0)] public global::MioGame.LZ4_streamDecode_t_internal internal_donotuse;
    #endregion
}
/// Struct type: LZ4_streamHC_u<br/>TypeIndex: 110804 (0x1C0D4)<br/>UniqueName: 
[StructLayout(LayoutKind.Explicit, Size = 262200)]
public partial struct LZ4_streamHC_u {
    #region Instance Fields
    /// Field: CsArray sbyte<br/>TypeIndex: 110801 (0x1C0D1)
    [FieldOffset(0)] public global::MioGame.InlineArray_CppChar_262200 minStateSize;
    /// Field: CsStruct LZ4HC_CCtx_internal<br/>TypeIndex: 110810 (0x1C0DA)
    [FieldOffset(0)] public global::MioGame.LZ4HC_CCtx_internal internal_donotuse;
    #endregion
}
/// Struct type: mi_page_flags_s<br/>TypeIndex: 1370 (0x155A)<br/>UniqueName: 
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct mi_page_flags_s {
    #region Instance Fields
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(0)] public CppUnsignedChar full_aligned;
    /// Field: CsStruct mi_page_flags_s__&lt;unnamed-tag&gt;<br/>TypeIndex: 1362 (0x1552)
    [FieldOffset(0)] public global::MioGame.mi_page_flags_s.unnamed_struct_1 x;
    #endregion
    #region Nested Types
    /// Struct type: mi_page_flags_s::&lt;unnamed-tag&gt;<br/>TypeIndex: 1362 (0x1552)<br/>UniqueName: 
    [StructLayout(LayoutKind.Explicit, Size = 1)]
    public partial struct unnamed_struct_1 {
        #region Instance Fields
        /// Field: unsigned char (UnsignedCharacter | Direct)
        [FieldOffset(0)] public CppUnsignedChar in_full;
        /// Field: unsigned char (UnsignedCharacter | Direct)
        [FieldOffset(0)] public CppUnsignedChar has_aligned;
        #endregion
    }
    #endregion
}
