// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame._;

/// Struct type: `anonymous-namespace&apos;::_Find_traits_1<br/>TypeIndex: 148369 (0x25391)<br/>UniqueName: .?AU_Find_traits_1@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Find_traits_1 {
}
/// Struct type: `anonymous-namespace&apos;::_Find_traits_2<br/>TypeIndex: 148143 (0x252AF)<br/>UniqueName: .?AU_Find_traits_2@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Find_traits_2 {
}
/// Struct type: `anonymous-namespace&apos;::_Find_traits_4<br/>TypeIndex: 148178 (0x252D2)<br/>UniqueName: .?AU_Find_traits_4@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Find_traits_4 {
}
/// Struct type: `anonymous-namespace&apos;::_Find_traits_8<br/>TypeIndex: 148236 (0x2530C)<br/>UniqueName: .?AU_Find_traits_8@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Find_traits_8 {
}
/// Enum type: `anonymous-namespace&apos;::_Min_max_mode<br/>UniqueName: .?AW4_Min_max_mode@?A0x8417fefe@@
public enum _Min_max_mode : CppInt32 {
    _Mode_min = 1,
    _Mode_max = 2,
    _Mode_both = 3,
}

/// Struct type: `anonymous-namespace&apos;::_Minmax_traits_1<br/>TypeIndex: 148211 (0x252F3)<br/>UniqueName: .?AU_Minmax_traits_1@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Minmax_traits_1 {
}
/// Struct type: `anonymous-namespace&apos;::_Minmax_traits_2<br/>TypeIndex: 148310 (0x25356)<br/>UniqueName: .?AU_Minmax_traits_2@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Minmax_traits_2 {
}
/// Struct type: `anonymous-namespace&apos;::_Minmax_traits_4<br/>TypeIndex: 148278 (0x25336)<br/>UniqueName: .?AU_Minmax_traits_4@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Minmax_traits_4 {
}
/// Struct type: `anonymous-namespace&apos;::_Minmax_traits_8<br/>TypeIndex: 148342 (0x25376)<br/>UniqueName: .?AU_Minmax_traits_8@?A0x8417fefe@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Minmax_traits_8 {
}
/// Struct type: `anonymous namespace&apos;::MyItem<br/>TypeIndex: 168535 (0x2A257)<br/>UniqueName: .?AUMyItem@?A0x9B08F338@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct MyItem {
    #region Memory Address Access
    public static class Pointers {
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame._.MyItem*, void*, void*, CppInt32> CompareWithSortSpecs = (delegate* unmanaged[Cdecl]<global::MioGame._.MyItem*, void*, void*, CppInt32>)(MioGameFunctionAddress + 13308880);
    }
    #endregion
    #region Static Fields
    /// Field: ImGuiTableSortSpecs*<br/>TypeIndex 167211 (0x29D2B)
    public static unsafe ref global::MioGame.ImGuiTableSortSpecs* s_current_sort_specs => ref *((global::MioGame.ImGuiTableSortSpecs**)(MioGameMemoryAddress + 18135968));
    #endregion
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 ID;
    /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
    [FieldOffset(8)] public CppChar* Name;
    /// Field: int (Int32 | Direct)
    [FieldOffset(16)] public CppInt32 Quantity;
    #endregion
    #region Instance Methods
    public unsafe CppInt32 CompareWithSortSpecs(void* lhs, void* rhs) {
        fixed (global::MioGame._.MyItem* pThis = &this) {
            return Pointers.CompareWithSortSpecs(pThis, lhs, rhs);
        }
    }
    #endregion
}
/// Enum type: `anonymous namespace&apos;::MyItemColumnID<br/>UniqueName: .?AW4MyItemColumnID@?A0x9B08F338@@
public enum MyItemColumnID : CppInt32 {
    MyItemColumnID_ID = 0,
    MyItemColumnID_Name = 1,
    MyItemColumnID_Action = 2,
    MyItemColumnID_Quantity = 3,
    MyItemColumnID_Description = 4,
}

