// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.@base;

/// [Forward Reference Only] Struct type: base::FilePath<br/>TypeIndex: 4416 (0x2140)<br/>UniqueName: .?AVFilePath@base@@
 public partial struct FilePath;
