// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.Concurrency;

/// Struct type: Concurrency::_Continuation_func_transformer&lt;void,void&gt;<br/>TypeIndex: 166798 (0x29B8E)<br/>UniqueName: .?AV?$_Continuation_func_transformer@XX@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Continuation_func_transformer_void_void {
}
/// Struct type: Concurrency::_Init_func_transformer&lt;void&gt;<br/>TypeIndex: 166765 (0x29B6D)<br/>UniqueName: .?AV?$_Init_func_transformer@X@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Init_func_transformer_void {
}
/// Struct type: Concurrency::cancellation_token<br/>TypeIndex: 167588 (0x29EA4)<br/>UniqueName: .?AVcancellation_token@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct cancellation_token {
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___CancellationTokenState*<br/>TypeIndex: 163583 (0x28EFF)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenState* _M_Impl;
    #endregion
}
/// Struct type: Concurrency::cancellation_token_registration<br/>TypeIndex: 167148 (0x29CEC)<br/>UniqueName: .?AVcancellation_token_registration@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct cancellation_token_registration {
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___CancellationTokenRegistration*<br/>TypeIndex: 163644 (0x28F3C)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenRegistration* _M_pRegistration;
    #endregion
}
/// Struct type: Concurrency::cancellation_token_source<br/>TypeIndex: 167238 (0x29D46)<br/>UniqueName: .?AVcancellation_token_source@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct cancellation_token_source {
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___CancellationTokenState*<br/>TypeIndex: 163583 (0x28EFF)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenState* _M_Impl;
    #endregion
}
/// Struct type: Concurrency::invalid_operation<br/>TypeIndex: 168276 (0x2A154)<br/>UniqueName: .?AVinvalid_operation@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct invalid_operation {
    #region Base Classes
    /// Base class: std::exception<br/>TypeIndex: 5032 (0x23A8)
    [FieldOffset(0)] public global::MioGame.std.exception Base;
    #endregion
}
/// Struct type: Concurrency::scheduler_interface<br/>TypeIndex: 166741 (0x29B55)<br/>UniqueName: .?AUscheduler_interface@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct scheduler_interface {
}
/// Struct type: Concurrency::scheduler_ptr<br/>TypeIndex: 167472 (0x29E30)<br/>UniqueName: .?AUscheduler_ptr@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct scheduler_ptr {
    #region Instance Fields
    /// Field: CsStruct std__shared_ptr&lt;Concurrency__scheduler_interface&gt;<br/>TypeIndex: 177271 (0x2C477)
    [FieldOffset(0)] public global::MioGame.std.shared_ptr_Concurrency__scheduler_interface _M_sharedScheduler;
    /// Field: CsPointerType Concurrency__scheduler_interface*<br/>TypeIndex: 167405 (0x29DED)
    [FieldOffset(16)] public global::MioGame.Concurrency.scheduler_interface* _M_scheduler;
    #endregion
}
/// Struct type: Concurrency::task_canceled<br/>TypeIndex: 168141 (0x2A0CD)<br/>UniqueName: .?AVtask_canceled@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct task_canceled {
    #region Base Classes
    /// Base class: std::exception<br/>TypeIndex: 5032 (0x23A8)
    [FieldOffset(0)] public global::MioGame.std.exception Base;
    #endregion
}
/// Struct type: Concurrency::task_completion_event&lt;unsigned char&gt;<br/>TypeIndex: 167732 (0x29F34)<br/>UniqueName: .?AV?$task_completion_event@E@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct task_completion_event_unsigned_char {
    #region Instance Fields
    /// Field: CsStruct std__shared_ptr&lt;Concurrency__details___Task_completion_event_impl&lt;unsigned char&gt; &gt;<br/>TypeIndex: 185502 (0x2E49E)
    [FieldOffset(0)] public global::MioGame.std.shared_ptr_Concurrency__details___Task_completion_event_impl_unsigned_char _M_Impl;
    #endregion
}
/// Struct type: Concurrency::task_completion_event&lt;void&gt;<br/>TypeIndex: 167849 (0x29FA9)<br/>UniqueName: .?AV?$task_completion_event@X@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct task_completion_event_void {
    #region Instance Fields
    /// Field: CsStruct Concurrency__task_completion_event&lt;unsigned char&gt;<br/>TypeIndex: 167732 (0x29F34)
    [FieldOffset(0)] public global::MioGame.Concurrency.task_completion_event_unsigned_char _M_unitEvent;
    #endregion
}
/// Struct type: Concurrency::task_continuation_context<br/>TypeIndex: 168202 (0x2A10A)<br/>UniqueName: .?AVtask_continuation_context@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct task_continuation_context {
    #region Base Classes
    /// Base class: Concurrency::details::_ContextCallback<br/>TypeIndex: 166595 (0x29AC3)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._ContextCallback Base;
    #endregion
    #region Instance Fields
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(8)] public bool _M_RunInline;
    #endregion
    #region Nested Types
    /// Struct type: Concurrency::task_continuation_context::_Tag<br/>TypeIndex: 168206 (0x2A10E)<br/>UniqueName: .?AU_Tag@task_continuation_context@Concurrency@@
    [StructLayout(LayoutKind.Explicit, Size = 1)]
    public partial struct _Tag {
    }
    #endregion
}
/// Enum type: Concurrency::task_group_status<br/>UniqueName: .?AW4task_group_status@Concurrency@@
public enum task_group_status : CppInt32 {
    not_complete = 0,
    completed = 1,
    canceled = 2,
}

/// Struct type: Concurrency::task_options<br/>TypeIndex: 166921 (0x29C09)<br/>UniqueName: .?AVtask_options@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 96)]
public partial struct task_options {
    #region Instance Fields
    /// Field: CsStruct Concurrency__scheduler_ptr<br/>TypeIndex: 167472 (0x29E30)
    [FieldOffset(0)] public global::MioGame.Concurrency.scheduler_ptr _M_Scheduler;
    /// Field: CsStruct Concurrency__cancellation_token<br/>TypeIndex: 167588 (0x29EA4)
    [FieldOffset(24)] public global::MioGame.Concurrency.cancellation_token _M_CancellationToken;
    /// Field: CsStruct Concurrency__task_continuation_context<br/>TypeIndex: 168202 (0x2A10A)
    [FieldOffset(32)] public global::MioGame.Concurrency.task_continuation_context _M_ContinuationContext;
    /// Field: CsStruct Concurrency__details___Internal_task_options<br/>TypeIndex: 166396 (0x299FC)
    [FieldOffset(48)] public global::MioGame.Concurrency.details._Internal_task_options _M_InternalTaskOptions;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(88)] public bool _M_HasCancellationToken;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(89)] public bool _M_HasScheduler;
    #endregion
}
/// Struct type: Concurrency::task&lt;unsigned __int64&gt;<br/>TypeIndex: 167034 (0x29C7A)<br/>UniqueName: .?AV?$task@_K@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct task_unsigned___int64 {
    #region Instance Fields
    /// Field: CsStruct std__shared_ptr&lt;Concurrency__details___Task_impl&lt;unsigned __int64&gt; &gt;<br/>TypeIndex: 169362 (0x2A592)
    [FieldOffset(0)] public global::MioGame.std.shared_ptr_Concurrency__details___Task_impl_unsigned___int64 _M_Impl;
    #endregion
}
/// Struct type: Concurrency::task&lt;unsigned char&gt;<br/>TypeIndex: 168038 (0x2A066)<br/>UniqueName: .?AV?$task@E@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct task_unsigned_char {
    #region Instance Fields
    /// Field: CsStruct std__shared_ptr&lt;Concurrency__details___Task_impl&lt;unsigned char&gt; &gt;<br/>TypeIndex: 183153 (0x2DB71)
    [FieldOffset(0)] public global::MioGame.std.shared_ptr_Concurrency__details___Task_impl_unsigned_char _M_Impl;
    #endregion
}
/// Struct type: Concurrency::task&lt;void&gt;<br/>TypeIndex: 167385 (0x29DD9)<br/>UniqueName: .?AV?$task@X@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct task_void {
    #region Instance Fields
    /// Field: CsStruct Concurrency__task&lt;unsigned char&gt;<br/>TypeIndex: 168038 (0x2A066)
    [FieldOffset(0)] public global::MioGame.Concurrency.task_unsigned_char _M_unitTask;
    #endregion
}
/// [Forward Reference Only] Struct type: Concurrency::task_completion_event&lt;unsigned __int64&gt;<br/>TypeIndex: 167004 (0x29C5C)<br/>UniqueName: .?AV?$task_completion_event@_K@Concurrency@@
 public partial struct task_completion_event_unsigned___int64;
