// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.Concurrency.details;

/// Struct type: Concurrency::details::_BadArgType<br/>TypeIndex: 164975 (0x2946F)<br/>UniqueName: .?AU_BadArgType@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _BadArgType {
}
/// Struct type: Concurrency::details::_BadContinuationParamType<br/>TypeIndex: 166295 (0x29997)<br/>UniqueName: .?AU_BadContinuationParamType@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _BadContinuationParamType {
}
/// Struct type: Concurrency::details::_CancellationTokenRegistration<br/>TypeIndex: 163981 (0x2908D)<br/>UniqueName: .?AV_CancellationTokenRegistration@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 192)]
public unsafe partial struct _CancellationTokenRegistration {
    #region Base Classes
    /// Base class: Concurrency::details::_RefCounter<br/>TypeIndex: 165004 (0x2948C)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._RefCounter Base;
    #endregion
    #region Static Fields
    /// Field: TypeIndex long (Int32Long | Direct) Value: 0 (C# Type: UInt16)
    public const CppInt32Long _STATE_CLEAR = (CppInt32Long)(0);
    /// Field: TypeIndex long (Int32Long | Direct) Value: 1 (C# Type: UInt16)
    public const CppInt32Long _STATE_DEFER_DELETE = (CppInt32Long)(1);
    /// Field: TypeIndex long (Int32Long | Direct) Value: 2 (C# Type: UInt16)
    public const CppInt32Long _STATE_SYNCHRONIZE = (CppInt32Long)(2);
    /// Field: TypeIndex long (Int32Long | Direct) Value: 3 (C# Type: UInt16)
    public const CppInt32Long _STATE_CALLED = (CppInt32Long)(3);
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__atomic&lt;long&gt;<br/>TypeIndex: 164973 (0x2946D)
    [FieldOffset(16)] public global::MioGame.std.atomic_long _M_state;
    /// Field: CsStruct std__condition_variable<br/>TypeIndex: 170004 (0x2A814)
    [FieldOffset(24)] public global::MioGame.std.condition_variable _M_CondVar;
    /// Field: CsStruct std__mutex<br/>TypeIndex: 180152 (0x2CFB8)
    [FieldOffset(96)] public global::MioGame.std.mutex _M_Mutex;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(176)] public bool _M_signaled;
    /// Field: CsPointerType Concurrency__details___CancellationTokenState*<br/>TypeIndex: 163583 (0x28EFF)
    [FieldOffset(184)] public global::MioGame.Concurrency.details._CancellationTokenState* _M_pTokenState;
    #endregion
}
/// Struct type: Concurrency::details::_CancellationTokenState<br/>TypeIndex: 163695 (0x28F6F)<br/>UniqueName: .?AV_CancellationTokenState@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 120)]
public partial struct _CancellationTokenState {
    #region Base Classes
    /// Base class: Concurrency::details::_RefCounter<br/>TypeIndex: 165004 (0x2948C)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._RefCounter Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__atomic&lt;long&gt;<br/>TypeIndex: 164973 (0x2946D)
    [FieldOffset(16)] public global::MioGame.std.atomic_long _M_stateFlag;
    /// Field: CsStruct std__mutex<br/>TypeIndex: 180152 (0x2CFB8)
    [FieldOffset(24)] public global::MioGame.std.mutex _M_listLock;
    /// Field: CsStruct Concurrency__details___CancellationTokenState__TokenRegistrationContainer<br/>TypeIndex: 163757 (0x28FAD)
    [FieldOffset(104)] public global::MioGame.Concurrency.details._CancellationTokenState.TokenRegistrationContainer _M_registrations;
    #endregion
    #region Nested Types
    /// Struct type: Concurrency::details::_CancellationTokenState::TokenRegistrationContainer<br/>TypeIndex: 163757 (0x28FAD)<br/>UniqueName: .?AVTokenRegistrationContainer@_CancellationTokenState@details@Concurrency@@
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct TokenRegistrationContainer {
        #region Instance Fields
        /// Field: CsPointerType Concurrency__details___CancellationTokenState__TokenRegistrationContainer___Node*<br/>TypeIndex: 163735 (0x28F97)
        [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenState.TokenRegistrationContainer.Node* _M_begin;
        /// Field: CsPointerType Concurrency__details___CancellationTokenState__TokenRegistrationContainer___Node*<br/>TypeIndex: 163735 (0x28F97)
        [FieldOffset(8)] public global::MioGame.Concurrency.details._CancellationTokenState.TokenRegistrationContainer.Node* _M_last;
        #endregion
        #region Nested Types
        /// Struct type: Concurrency::details::_CancellationTokenState::TokenRegistrationContainer::_Node<br/>TypeIndex: 163773 (0x28FBD)<br/>UniqueName: .?AU_Node@TokenRegistrationContainer@_CancellationTokenState@details@Concurrency@@
        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public unsafe partial struct Node {
            #region Instance Fields
            /// Field: CsPointerType Concurrency__details___CancellationTokenRegistration*<br/>TypeIndex: 163644 (0x28F3C)
            [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenRegistration* _M_token;
            /// Field: CsPointerType Concurrency__details___CancellationTokenState__TokenRegistrationContainer___Node*<br/>TypeIndex: 163735 (0x28F97)
            [FieldOffset(8)] public global::MioGame.Concurrency.details._CancellationTokenState.TokenRegistrationContainer.Node* _M_next;
            #endregion
        }
        #endregion
    }
    #endregion
}
/// Struct type: Concurrency::details::_ContextCallback<br/>TypeIndex: 166595 (0x29AC3)<br/>UniqueName: .?AV_ContextCallback@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _ContextCallback {
    #region Static Fields
    /// Field: TypeIndex unsigned __int64 (UInt64Quad | Direct) Value: 1 (C# Type: UInt16)
    public const CppUInt64Quad _S_captureDeferred = (CppUInt64Quad)(1);
    #endregion
    #region Instance Fields
    /// Field: CsUnion Concurrency__details___ContextCallback__&lt;unnamed-type-_M_context&gt;<br/>TypeIndex: 166599 (0x29AC7)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._ContextCallback._M_context _m_context;
    #endregion
    #region Nested Types
    /// Struct type: Concurrency::details::_ContextCallback::&lt;unnamed-type-_M_context&gt;<br/>TypeIndex: 166599 (0x29AC7)<br/>UniqueName: .?AT&lt;unnamed-type-_M_context&gt;@_ContextCallback@details@Concurrency@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct _M_context {
        #region Instance Fields
        /// Field: void* (Void | NearPointer64)
        [FieldOffset(0)] public void* _M_pContextCallback;
        /// Field: unsigned __int64 (UInt64Quad | Direct)
        [FieldOffset(0)] public CppUInt64Quad _M_captureMethod;
        #endregion
    }
    #endregion
}
/// Struct type: Concurrency::details::_ContinuationTaskHandleBase<br/>TypeIndex: 165611 (0x296EB)<br/>UniqueName: .?AU_ContinuationTaskHandleBase@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 40)]
public unsafe partial struct _ContinuationTaskHandleBase {
    #region Base Classes
    /// Base class: Concurrency::details::_TaskProcHandle<br/>TypeIndex: 164471 (0x29277)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._TaskProcHandle Base;
    #endregion
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___ContinuationTaskHandleBase*<br/>TypeIndex: 165565 (0x296BD)
    [FieldOffset(8)] public global::MioGame.Concurrency.details._ContinuationTaskHandleBase* _M_next;
    /// Field: CsStruct Concurrency__task_continuation_context<br/>TypeIndex: 168202 (0x2A10A)
    [FieldOffset(16)] public global::MioGame.Concurrency.task_continuation_context _M_continuationContext;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(32)] public bool _M_isTaskBasedContinuation;
    /// Field: CsEnum Concurrency__details___TaskInliningMode<br/>TypeIndex: 163124 (0x28D34)
    [FieldOffset(36)] public global::MioGame.Concurrency.details._TaskInliningMode _M_inliningMode;
    #endregion
}
/// Struct type: Concurrency::details::_DefaultPPLTaskScheduler<br/>TypeIndex: 165158 (0x29526)<br/>UniqueName: .?AV_DefaultPPLTaskScheduler@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _DefaultPPLTaskScheduler {
    #region Base Classes
    /// Base class: Concurrency::scheduler_interface<br/>TypeIndex: 166741 (0x29B55)
    [FieldOffset(0)] public global::MioGame.Concurrency.scheduler_interface Base;
    #endregion
}
/// Struct type: Concurrency::details::_DefaultTaskHelper<br/>TypeIndex: 166329 (0x299B9)<br/>UniqueName: .?AU_DefaultTaskHelper@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _DefaultTaskHelper {
}
/// Struct type: Concurrency::details::_ExceptionHolder<br/>TypeIndex: 166310 (0x299A6)<br/>UniqueName: .?AU_ExceptionHolder@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 56)]
public partial struct _ExceptionHolder {
    #region Instance Fields
    /// Field: CsStruct std__atomic&lt;long&gt;<br/>TypeIndex: 164973 (0x2946D)
    [FieldOffset(0)] public global::MioGame.std.atomic_long _M_exceptionObserved;
    /// Field: CsStruct std__exception_ptr<br/>TypeIndex: 180434 (0x2D0D2)
    [FieldOffset(8)] public global::MioGame.std.exception_ptr _M_stdException;
    /// Field: CsStruct Concurrency__details___TaskCreationCallstack<br/>TypeIndex: 165078 (0x294D6)
    [FieldOffset(24)] public global::MioGame.Concurrency.details._TaskCreationCallstack _M_stackTrace;
    #endregion
}
/// Struct type: Concurrency::details::_Internal_task_options<br/>TypeIndex: 166396 (0x299FC)<br/>UniqueName: .?AU_Internal_task_options@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 40)]
public partial struct _Internal_task_options {
    #region Instance Fields
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(0)] public bool _M_hasPresetCreationCallstack;
    /// Field: CsStruct Concurrency__details___TaskCreationCallstack<br/>TypeIndex: 165078 (0x294D6)
    [FieldOffset(8)] public global::MioGame.Concurrency.details._TaskCreationCallstack _M_presetCreationCallstack;
    #endregion
}
/// Struct type: Concurrency::details::_Interruption_exception<br/>TypeIndex: 163941 (0x29065)<br/>UniqueName: .?AV_Interruption_exception@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct _Interruption_exception {
    #region Base Classes
    /// Base class: std::exception<br/>TypeIndex: 5032 (0x23A8)
    [FieldOffset(0)] public global::MioGame.std.exception Base;
    #endregion
}
/// Struct type: Concurrency::details::_IsUnwrappedAsyncSelector&lt;Concurrency::details::_TypeSelectorNoAsync&gt;<br/>TypeIndex: 164952 (0x29458)<br/>UniqueName: .?AU?$_IsUnwrappedAsyncSelector@U_TypeSelectorNoAsync@details@Concurrency@@@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _IsUnwrappedAsyncSelector_Concurrency__details___TypeSelectorNoAsync {
    #region Static Fields
    /// Field: TypeIndex bool (Boolean8 | Direct) Value: 0 (C# Type: UInt16)
    public const bool _Value = false;
    #endregion
}
/// Struct type: Concurrency::details::_NormalizeVoidToUnitType&lt;void&gt;<br/>TypeIndex: 166156 (0x2990C)<br/>UniqueName: .?AU?$_NormalizeVoidToUnitType@X@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _NormalizeVoidToUnitType_void {
}
/// Struct type: Concurrency::details::_ProgressReporterCtorArgType<br/>TypeIndex: 166601 (0x29AC9)<br/>UniqueName: .?AV_ProgressReporterCtorArgType@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _ProgressReporterCtorArgType {
}
/// Struct type: Concurrency::details::_RefCounter<br/>TypeIndex: 165004 (0x2948C)<br/>UniqueName: .?AV_RefCounter@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct _RefCounter {
    #region Instance Fields
    /// Field: long (Int32Long | Direct)
    [FieldOffset(8)] public CppInt32Long _M_refCount;
    #endregion
}
/// Struct type: Concurrency::details::_ResultHolder&lt;std::vector&lt;bool,std::allocator&lt;bool&gt; &gt; &gt;<br/>TypeIndex: 165851 (0x297DB)<br/>UniqueName: .?AU?$_ResultHolder@V?$vector@_NV?$allocator@_N@std@@@std@@@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct _ResultHolder_std__vector_bool_std__allocator_bool {
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;char,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 150352 (0x25B50)
    [FieldOffset(0)] public global::MioGame.std.vector_char_std__allocator_char _Result;
    #endregion
}
/// Struct type: Concurrency::details::_ResultHolder&lt;unsigned char&gt;<br/>TypeIndex: 166480 (0x29A50)<br/>UniqueName: .?AU?$_ResultHolder@E@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _ResultHolder_unsigned_char {
    #region Instance Fields
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(0)] public CppUnsignedChar _Result;
    #endregion
}
/// Struct type: Concurrency::details::_RunAllParam&lt;unsigned char&gt;<br/>TypeIndex: 165031 (0x294A7)<br/>UniqueName: .?AU?$_RunAllParam@E@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct _RunAllParam_unsigned_char {
    #region Instance Fields
    /// Field: CsStruct Concurrency__task_completion_event&lt;unsigned char&gt;<br/>TypeIndex: 167732 (0x29F34)
    [FieldOffset(0)] public global::MioGame.Concurrency.task_completion_event_unsigned_char _M_completed;
    /// Field: CsStruct std__atomic&lt;unsigned __int64&gt;<br/>TypeIndex: 164921 (0x29439)
    [FieldOffset(16)] public global::MioGame.std.atomic_unsigned___int64 _M_completeCount;
    /// Field: unsigned __int64 (UInt64Quad | Direct)
    [FieldOffset(24)] public CppUInt64Quad _M_numTasks;
    #endregion
}
/// Struct type: Concurrency::details::_Task_completion_event_impl&lt;unsigned char&gt;<br/>TypeIndex: 164189 (0x2915D)<br/>UniqueName: .?AU?$_Task_completion_event_impl@E@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 136)]
public partial struct _Task_completion_event_impl_unsigned_char {
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;std__shared_ptr&lt;Concurrency__details___Task_impl&lt;unsigned char&gt; &gt;,std__allocator&lt;std__shared_ptr&lt;Concurrency__details___Task_impl&lt;unsigned char&gt; &gt; &gt; &gt;<br/>TypeIndex: 179892 (0x2CEB4)
    [FieldOffset(0)] public global::MioGame.std.vector_std__shared_ptr_Concurrency__details___Task_impl_unsigned_char_std__allocator_std__shared_ptr_Concurrency__details___Task_impl_unsigned_char _M_tasks;
    /// Field: CsStruct std__mutex<br/>TypeIndex: 180152 (0x2CFB8)
    [FieldOffset(24)] public global::MioGame.std.mutex _M_taskListCritSec;
    /// Field: CsStruct Concurrency__details___ResultHolder&lt;unsigned char&gt;<br/>TypeIndex: 166480 (0x29A50)
    [FieldOffset(104)] public global::MioGame.Concurrency.details._ResultHolder_unsigned_char _M_value;
    /// Field: CsStruct std__shared_ptr&lt;Concurrency__details___ExceptionHolder&gt;<br/>TypeIndex: 172545 (0x2B201)
    [FieldOffset(112)] public global::MioGame.std.shared_ptr_Concurrency__details___ExceptionHolder _M_exceptionHolder;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(128)] public bool _M_fHasValue;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(129)] public bool _M_fIsCanceled;
    #endregion
}
/// Struct type: Concurrency::details::_Task_generator_oversubscriber<br/>TypeIndex: 163290 (0x28DDA)<br/>UniqueName: .?AU_Task_generator_oversubscriber@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Task_generator_oversubscriber {
}
/// Struct type: Concurrency::details::_Task_impl_base<br/>TypeIndex: 166149 (0x29905)<br/>UniqueName: .?AU_Task_impl_base@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 368)]
public unsafe partial struct _Task_impl_base {
    #region Instance Fields
    /// Field: CsEnum Concurrency__details___Task_impl_base___TaskInternalState<br/>TypeIndex: 165988 (0x29864)
    [FieldOffset(8)] public global::MioGame.Concurrency.details._Task_impl_base._TaskInternalState _M_TaskState;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(12)] public bool _M_fFromAsync;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(13)] public bool _M_fUnwrappedTask;
    /// Field: CsStruct std__shared_ptr&lt;Concurrency__details___ExceptionHolder&gt;<br/>TypeIndex: 172545 (0x2B201)
    [FieldOffset(16)] public global::MioGame.std.shared_ptr_Concurrency__details___ExceptionHolder _M_exceptionHolder;
    /// Field: CsStruct std__mutex<br/>TypeIndex: 180152 (0x2CFB8)
    [FieldOffset(32)] public global::MioGame.std.mutex _M_ContinuationsCritSec;
    /// Field: CsPointerType Concurrency__details___ContinuationTaskHandleBase*<br/>TypeIndex: 165565 (0x296BD)
    [FieldOffset(112)] public global::MioGame.Concurrency.details._ContinuationTaskHandleBase* _M_Continuations;
    /// Field: CsPointerType Concurrency__details___CancellationTokenState*<br/>TypeIndex: 163583 (0x28EFF)
    [FieldOffset(120)] public global::MioGame.Concurrency.details._CancellationTokenState* _M_pTokenState;
    /// Field: CsPointerType Concurrency__details___CancellationTokenRegistration*<br/>TypeIndex: 163644 (0x28F3C)
    [FieldOffset(128)] public global::MioGame.Concurrency.details._CancellationTokenRegistration* _M_pRegistration;
    /// Field: CsStruct Concurrency__details___TaskCollectionBaseImpl<br/>TypeIndex: 165430 (0x29636)
    [FieldOffset(136)] public global::MioGame.Concurrency.details._TaskCollectionBaseImpl _M_TaskCollection;
    /// Field: CsStruct Concurrency__details___TaskCreationCallstack<br/>TypeIndex: 165078 (0x294D6)
    [FieldOffset(320)] public global::MioGame.Concurrency.details._TaskCreationCallstack _M_pTaskCreationCallstack;
    /// Field: CsStruct Concurrency__details___TaskEventLogger<br/>TypeIndex: 166225 (0x29951)
    [FieldOffset(352)] public global::MioGame.Concurrency.details._TaskEventLogger _M_taskEventLogger;
    #endregion
    #region Nested Types
    /// Enum type: Concurrency::details::_Task_impl_base::_TaskInternalState<br/>UniqueName: .?AW4_TaskInternalState@_Task_impl_base@details@Concurrency@@
    public enum _TaskInternalState : CppInt32 {
        _Created = 0,
        _Started = 1,
        _PendingCancel = 2,
        _Completed = 3,
        _Canceled = 4,
    }
    
    #endregion
}
/// Struct type: Concurrency::details::_Task_impl&lt;unsigned char&gt;<br/>TypeIndex: 165298 (0x295B2)<br/>UniqueName: .?AU?$_Task_impl@E@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 440)]
public partial struct _Task_impl_unsigned_char {
    #region Base Classes
    /// Base class: Concurrency::details::_Task_impl_base<br/>TypeIndex: 166149 (0x29905)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._Task_impl_base Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct Concurrency__details___ResultHolder&lt;unsigned char&gt;<br/>TypeIndex: 166480 (0x29A50)
    [FieldOffset(368)] public global::MioGame.Concurrency.details._ResultHolder_unsigned_char _M_Result;
    /// Field: CsStruct std__function&lt;void __cdecl(void)&gt;<br/>TypeIndex: 174779 (0x2BABB)
    [FieldOffset(376)] public global::MioGame.std.function_void___cdecl_void _M_InternalCancellation;
    #endregion
}
/// Struct type: Concurrency::details::_Task_ptr&lt;unsigned __int64&gt;<br/>TypeIndex: 165635 (0x29703)<br/>UniqueName: .?AU?$_Task_ptr@_K@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Task_ptr_unsigned___int64 {
}
/// Struct type: Concurrency::details::_Task_ptr&lt;unsigned char&gt;<br/>TypeIndex: 165698 (0x29742)<br/>UniqueName: .?AU?$_Task_ptr@E@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _Task_ptr_unsigned_char {
}
/// Struct type: Concurrency::details::_TaskCollectionBaseImpl<br/>TypeIndex: 165430 (0x29636)<br/>UniqueName: .?AV_TaskCollectionBaseImpl@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 184)]
public partial struct _TaskCollectionBaseImpl {
    #region Instance Fields
    /// Field: CsStruct std__condition_variable<br/>TypeIndex: 170004 (0x2A814)
    [FieldOffset(0)] public global::MioGame.std.condition_variable _M_StateChanged;
    /// Field: CsStruct std__mutex<br/>TypeIndex: 180152 (0x2CFB8)
    [FieldOffset(72)] public global::MioGame.std.mutex _M_Cs;
    /// Field: CsStruct Concurrency__scheduler_ptr<br/>TypeIndex: 167472 (0x29E30)
    [FieldOffset(152)] public global::MioGame.Concurrency.scheduler_ptr _M_pScheduler;
    /// Field: CsEnum Concurrency__details___TaskCollectionBaseImpl___TaskCollectionState<br/>TypeIndex: 165325 (0x295CD)
    [FieldOffset(176)] public global::MioGame.Concurrency.details._TaskCollectionBaseImpl._TaskCollectionState _M_State;
    #endregion
    #region Nested Types
    /// Enum type: Concurrency::details::_TaskCollectionBaseImpl::_TaskCollectionState<br/>UniqueName: .?AW4_TaskCollectionState@_TaskCollectionBaseImpl@details@Concurrency@@
    public enum _TaskCollectionState : CppInt32 {
        _New = 0,
        _Scheduled = 1,
        _Completed = 2,
    }
    
    #endregion
}
/// Struct type: Concurrency::details::_TaskCreationCallstack<br/>TypeIndex: 165078 (0x294D6)<br/>UniqueName: .?AV_TaskCreationCallstack@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public unsafe partial struct _TaskCreationCallstack {
    #region Instance Fields
    /// Field: void* (Void | NearPointer64)
    [FieldOffset(0)] public void* _M_SingleFrame;
    /// Field: CsStruct std__vector&lt;void *,std__allocator&lt;void *&gt; &gt;<br/>TypeIndex: 175212 (0x2BC6C)
    [FieldOffset(8)] public global::MioGame.std.vector_void_Ptr_std__allocator_void_Ptr _M_frames;
    #endregion
}
/// Struct type: Concurrency::details::_TaskEventLogger<br/>TypeIndex: 166225 (0x29951)<br/>UniqueName: .?AU_TaskEventLogger@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct _TaskEventLogger {
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___Task_impl_base*<br/>TypeIndex: 166190 (0x2992E)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._Task_impl_base* _M_task;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(8)] public bool _M_scheduled;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(9)] public bool _M_taskPostEventStarted;
    #endregion
}
/// Enum type: Concurrency::details::_TaskInliningMode<br/>UniqueName: .?AW4_TaskInliningMode@details@Concurrency@@
public enum _TaskInliningMode : CppInt32 {
    _NoInline = 0,
    _DefaultAutoInline = 16,
    _ForceInline = -1,
}

/// Struct type: Concurrency::details::_TaskProcHandle<br/>TypeIndex: 164471 (0x29277)<br/>UniqueName: .?AU_TaskProcHandle@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct _TaskProcHandle {
}
/// Struct type: Concurrency::details::_TaskProcThunk<br/>TypeIndex: 164331 (0x291EB)<br/>UniqueName: .?AU_TaskProcThunk@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 64)]
public partial struct _TaskProcThunk {
    #region Instance Fields
    /// Field: CsStruct std__function&lt;void __cdecl(void)&gt;<br/>TypeIndex: 174779 (0x2BABB)
    [FieldOffset(0)] public global::MioGame.std.function_void___cdecl_void _M_func;
    #endregion
    #region Nested Types
    /// Struct type: Concurrency::details::_TaskProcThunk::_Holder<br/>TypeIndex: 164420 (0x29244)<br/>UniqueName: .?AU_Holder@_TaskProcThunk@details@Concurrency@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct _Holder {
        #region Instance Fields
        /// Field: CsPointerType Concurrency__details___TaskProcThunk*<br/>TypeIndex: 164343 (0x291F7)
        [FieldOffset(0)] public global::MioGame.Concurrency.details._TaskProcThunk* _M_pThunk;
        #endregion
    }
    #endregion
}
/// Struct type: Concurrency::details::_TaskTypeFromParam&lt;Concurrency::task_completion_event&lt;void&gt; &gt;<br/>TypeIndex: 164950 (0x29456)<br/>UniqueName: .?AU?$_TaskTypeFromParam@V?$task_completion_event@X@Concurrency@@@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TaskTypeFromParam_Concurrency__task_completion_event_void {
}
/// Struct type: Concurrency::details::_TaskTypeTraits&lt;void,0&gt;<br/>TypeIndex: 166255 (0x2996F)<br/>UniqueName: .?AU?$_TaskTypeTraits@X$0A@@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TaskTypeTraits_void_0 {
    #region Static Fields
    /// Field: TypeIndex bool (Boolean8 | Direct) Value: 0 (C# Type: UInt16)
    public const bool _IsAsyncTask = false;
    /// Field: TypeIndex bool (Boolean8 | Direct) Value: 0 (C# Type: UInt16)
    public const bool _IsUnwrappedTaskOrAsync = false;
    #endregion
}
/// Struct type: Concurrency::details::_TaskWorkItemRAIILogger<br/>TypeIndex: 164654 (0x2932E)<br/>UniqueName: .?AU_TaskWorkItemRAIILogger@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct _TaskWorkItemRAIILogger {
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___TaskEventLogger&amp;<br/>TypeIndex: 164577 (0x292E1)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._TaskEventLogger* _M_logger;
    #endregion
}
/// Struct type: Concurrency::details::_ThenImplOptions<br/>TypeIndex: 164829 (0x293DD)<br/>UniqueName: .?AU_ThenImplOptions@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 80)]
public unsafe partial struct _ThenImplOptions {
    #region Instance Fields
    /// Field: CsPointerType Concurrency__details___CancellationTokenState*<br/>TypeIndex: 163583 (0x28EFF)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenState* _PTokenState;
    /// Field: CsStruct Concurrency__scheduler_ptr<br/>TypeIndex: 167472 (0x29E30)
    [FieldOffset(8)] public global::MioGame.Concurrency.scheduler_ptr _Scheduler;
    /// Field: CsStruct Concurrency__details___TaskCreationCallstack<br/>TypeIndex: 165078 (0x294D6)
    [FieldOffset(32)] public global::MioGame.Concurrency.details._TaskCreationCallstack _CreationStack;
    /// Field: CsEnum Concurrency__details___TaskInliningMode<br/>TypeIndex: 163124 (0x28D34)
    [FieldOffset(64)] public global::MioGame.Concurrency.details._TaskInliningMode _InliningMode;
    /// Field: CsPointerType Concurrency__task_continuation_context*<br/>TypeIndex: 164746 (0x2938A)
    [FieldOffset(72)] public global::MioGame.Concurrency.task_continuation_context* _PContinuationContext;
    #endregion
}
/// Struct type: Concurrency::details::_Threadpool_chore<br/>TypeIndex: 166245 (0x29965)<br/>UniqueName: .?AU_Threadpool_chore@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct _Threadpool_chore {
    #region Instance Fields
    /// Field: void* (Void | NearPointer64)
    [FieldOffset(0)] public void* _M_work;
    /// Field: void* (Void | NearPointer64)
    [FieldOffset(16)] public void* _M_data;
    #endregion
}
/// Struct type: Concurrency::details::_Threadpool_task<br/>TypeIndex: 165524 (0x29694)<br/>UniqueName: .?AV_Threadpool_task@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct _Threadpool_task {
    #region Instance Fields
    /// Field: CsStruct Concurrency__details___Threadpool_chore<br/>TypeIndex: 166245 (0x29965)
    [FieldOffset(8)] public global::MioGame.Concurrency.details._Threadpool_chore _M_chore;
    #endregion
}
/// Struct type: Concurrency::details::_TypeSelectorAsyncAction<br/>TypeIndex: 163539 (0x28ED3)<br/>UniqueName: .?AU_TypeSelectorAsyncAction@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorAsyncAction {
}
/// Struct type: Concurrency::details::_TypeSelectorAsyncActionWithProgress<br/>TypeIndex: 166612 (0x29AD4)<br/>UniqueName: .?AU_TypeSelectorAsyncActionWithProgress@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorAsyncActionWithProgress {
}
/// Struct type: Concurrency::details::_TypeSelectorAsyncOperation<br/>TypeIndex: 166609 (0x29AD1)<br/>UniqueName: .?AU_TypeSelectorAsyncOperation@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorAsyncOperation {
    #region Base Classes
    /// Base class: Concurrency::details::_TypeSelectorAsyncOperationOrTask<br/>TypeIndex: 166604 (0x29ACC)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._TypeSelectorAsyncOperationOrTask Base;
    #endregion
}
/// Struct type: Concurrency::details::_TypeSelectorAsyncOperationOrTask<br/>TypeIndex: 166604 (0x29ACC)<br/>UniqueName: .?AU_TypeSelectorAsyncOperationOrTask@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorAsyncOperationOrTask {
}
/// Struct type: Concurrency::details::_TypeSelectorAsyncOperationWithProgress<br/>TypeIndex: 166426 (0x29A1A)<br/>UniqueName: .?AU_TypeSelectorAsyncOperationWithProgress@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorAsyncOperationWithProgress {
}
/// Struct type: Concurrency::details::_TypeSelectorAsyncTask<br/>TypeIndex: 165554 (0x296B2)<br/>UniqueName: .?AU_TypeSelectorAsyncTask@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorAsyncTask {
    #region Base Classes
    /// Base class: Concurrency::details::_TypeSelectorAsyncOperationOrTask<br/>TypeIndex: 166604 (0x29ACC)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._TypeSelectorAsyncOperationOrTask Base;
    #endregion
}
/// Struct type: Concurrency::details::_TypeSelectorNoAsync<br/>TypeIndex: 166175 (0x2991F)<br/>UniqueName: .?AU_TypeSelectorNoAsync@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct _TypeSelectorNoAsync {
}
/// Struct type: Concurrency::details::CancellationTokenRegistration_TaskProc<br/>TypeIndex: 164558 (0x292CE)<br/>UniqueName: .?AVCancellationTokenRegistration_TaskProc@details@Concurrency@@
[StructLayout(LayoutKind.Explicit, Size = 208)]
public unsafe partial struct CancellationTokenRegistration_TaskProc {
    #region Base Classes
    /// Base class: Concurrency::details::_CancellationTokenRegistration<br/>TypeIndex: 163981 (0x2908D)
    [FieldOffset(0)] public global::MioGame.Concurrency.details._CancellationTokenRegistration Base;
    #endregion
    #region Instance Fields
    /// Field: void* (Void | NearPointer64)
    [FieldOffset(200)] public void* _M_pData;
    #endregion
}
/// [Forward Reference Only] Struct type: Concurrency::details::_Task_impl&lt;unsigned __int64&gt;<br/>TypeIndex: 170492 (0x2A9FC)<br/>UniqueName: .?AU?$_Task_impl@_K@details@Concurrency@@
 public partial struct _Task_impl_unsigned___int64;
