// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.D2D1;

/// Struct type: D2D1::ColorF<br/>TypeIndex: 153668 (0x26844)<br/>UniqueName: .?AVColorF@D2D1@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct ColorF {
    #region Base Classes
    /// Base class: _D3DCOLORVALUE<br/>TypeIndex: 153605 (0x26805)
    [FieldOffset(0)] public global::MioGame._D3DCOLORVALUE Base;
    #endregion
    #region Static Fields
    /// Field: TypeIndex unsigned (UInt32 | Direct) Value: 16 (C# Type: UInt16)
    public const CppUInt32 sc_redShift = (CppUInt32)(16);
    /// Field: TypeIndex unsigned (UInt32 | Direct) Value: 8 (C# Type: UInt16)
    public const CppUInt32 sc_greenShift = (CppUInt32)(8);
    /// Field: TypeIndex unsigned (UInt32 | Direct) Value: 0 (C# Type: UInt16)
    public const CppUInt32 sc_blueShift = (CppUInt32)(0);
    /// Field: TypeIndex unsigned (UInt32 | Direct) Value: 16711680 (C# Type: UInt32)
    public const CppUInt32 sc_redMask = (CppUInt32)(16711680);
    /// Field: TypeIndex unsigned (UInt32 | Direct) Value: 65280 (C# Type: UInt16)
    public const CppUInt32 sc_greenMask = (CppUInt32)(65280);
    /// Field: TypeIndex unsigned (UInt32 | Direct) Value: 255 (C# Type: UInt16)
    public const CppUInt32 sc_blueMask = (CppUInt32)(255);
    #endregion
    #region Nested Types
    /// Enum type: D2D1::ColorF::Enum<br/>UniqueName: .?AW4Enum@ColorF@D2D1@@
    public enum Enum : CppInt32 {
        AliceBlue = 15792383,
        AntiqueWhite = 16444375,
        Aqua = 65535,
        Aquamarine = 8388564,
        Azure = 15794175,
        Beige = 16119260,
        Bisque = 16770244,
        Black = 0,
        BlanchedAlmond = 16772045,
        Blue = 255,
        BlueViolet = 9055202,
        Brown = 10824234,
        BurlyWood = 14596231,
        CadetBlue = 6266528,
        Chartreuse = 8388352,
        Chocolate = 13789470,
        Coral = 16744272,
        CornflowerBlue = 6591981,
        Cornsilk = 16775388,
        Crimson = 14423100,
        Cyan = 65535,
        DarkBlue = 139,
        DarkCyan = 35723,
        DarkGoldenrod = 12092939,
        DarkGray = 11119017,
        DarkGreen = 25600,
        DarkKhaki = 12433259,
        DarkMagenta = 9109643,
        DarkOliveGreen = 5597999,
        DarkOrange = 16747520,
        DarkOrchid = 10040012,
        DarkRed = 9109504,
        DarkSalmon = 15308410,
        DarkSeaGreen = 9419919,
        DarkSlateBlue = 4734347,
        DarkSlateGray = 3100495,
        DarkTurquoise = 52945,
        DarkViolet = 9699539,
        DeepPink = 16716947,
        DeepSkyBlue = 49151,
        DimGray = 6908265,
        DodgerBlue = 2003199,
        Firebrick = 11674146,
        FloralWhite = 16775920,
        ForestGreen = 2263842,
        Fuchsia = 16711935,
        Gainsboro = 14474460,
        GhostWhite = 16316671,
        Gold = 16766720,
        Goldenrod = 14329120,
        Gray = 8421504,
        Green = 32768,
        GreenYellow = 11403055,
        Honeydew = 15794160,
        HotPink = 16738740,
        IndianRed = 13458524,
        Indigo = 4915330,
        Ivory = 16777200,
        Khaki = 15787660,
        Lavender = 15132410,
        LavenderBlush = 16773365,
        LawnGreen = 8190976,
        LemonChiffon = 16775885,
        LightBlue = 11393254,
        LightCoral = 15761536,
        LightCyan = 14745599,
        LightGoldenrodYellow = 16448210,
        LightGreen = 9498256,
        LightGray = 13882323,
        LightPink = 16758465,
        LightSalmon = 16752762,
        LightSeaGreen = 2142890,
        LightSkyBlue = 8900346,
        LightSlateGray = 7833753,
        LightSteelBlue = 11584734,
        LightYellow = 16777184,
        Lime = 65280,
        LimeGreen = 3329330,
        Linen = 16445670,
        Magenta = 16711935,
        Maroon = 8388608,
        MediumAquamarine = 6737322,
        MediumBlue = 205,
        MediumOrchid = 12211667,
        MediumPurple = 9662683,
        MediumSeaGreen = 3978097,
        MediumSlateBlue = 8087790,
        MediumSpringGreen = 64154,
        MediumTurquoise = 4772300,
        MediumVioletRed = 13047173,
        MidnightBlue = 1644912,
        MintCream = 16121850,
        MistyRose = 16770273,
        Moccasin = 16770229,
        NavajoWhite = 16768685,
        Navy = 128,
        OldLace = 16643558,
        Olive = 8421376,
        OliveDrab = 7048739,
        Orange = 16753920,
        OrangeRed = 16729344,
        Orchid = 14315734,
        PaleGoldenrod = 15657130,
        PaleGreen = 10025880,
        PaleTurquoise = 11529966,
        PaleVioletRed = 14381203,
        PapayaWhip = 16773077,
        PeachPuff = 16767673,
        Peru = 13468991,
        Pink = 16761035,
        Plum = 14524637,
        PowderBlue = 11591910,
        Purple = 8388736,
        Red = 16711680,
        RosyBrown = 12357519,
        RoyalBlue = 4286945,
        SaddleBrown = 9127187,
        Salmon = 16416882,
        SandyBrown = 16032864,
        SeaGreen = 3050327,
        SeaShell = 16774638,
        Sienna = 10506797,
        Silver = 12632256,
        SkyBlue = 8900331,
        SlateBlue = 6970061,
        SlateGray = 7372944,
        Snow = 16775930,
        SpringGreen = 65407,
        SteelBlue = 4620980,
        Tan = 13808780,
        Teal = 32896,
        Thistle = 14204888,
        Tomato = 16737095,
        Turquoise = 4251856,
        Violet = 15631086,
        Wheat = 16113331,
        White = 16777215,
        WhiteSmoke = 16119285,
        Yellow = 16776960,
        YellowGreen = 10145074,
    }
    
    #endregion
}
