// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.DDS;

/// Struct type: DDS::DDS<br/>TypeIndex: 145055 (0x2469F)<br/>UniqueName: .?AUDDS@0@
[StructLayout(LayoutKind.Explicit, Size = 168)]
public partial struct DDS {
    #region Instance Fields
    /// Field: CsStruct DDS__DDS__Header<br/>TypeIndex: 145061 (0x246A5)
    [FieldOffset(0)] public global::MioGame.DDS.DDS.Header header;
    /// Field: CsStruct DDS__DDS__Header_dx10<br/>TypeIndex: 145065 (0x246A9)
    [FieldOffset(124)] public global::MioGame.DDS.DDS.Header_dx10 header_dx10;
    /// Field: CsStruct Array&lt;unsigned char&gt;<br/>TypeIndex: 1214 (0x14BE)
    [FieldOffset(144)] public global::MioGame.Array_unsigned_char raw_data;
    /// Field: CsEnum DDS__Storage_format<br/>TypeIndex: 145004 (0x2466C)
    [FieldOffset(160)] public global::MioGame.DDS.DDS.Storage_format storage_format;
    #endregion
    #region Nested Types
    /// Struct type: DDS::DDS::Header<br/>TypeIndex: 145061 (0x246A5)<br/>UniqueName: .?AUHeader@DDS@1@
    [StructLayout(LayoutKind.Explicit, Size = 124)]
    public partial struct Header {
        #region Instance Fields
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 size;
        /// Field: CsEnum DDS__Flags<br/>TypeIndex: 145010 (0x24672)
        [FieldOffset(4)] public global::MioGame.DDS.DDS.Flags flags;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(8)] public CppUInt32 height;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(12)] public CppUInt32 width;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(16)] public CppUInt32 pitch_or_linear_size;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(20)] public CppUInt32 depth;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(24)] public CppUInt32 mipmap_count;
        /// Field: CsArray uint<br/>TypeIndex: 145056 (0x246A0)
        [FieldOffset(28)] public global::MioGame.InlineArray_CppUInt32_11 reserved_1;
        /// Field: CsStruct DDS__DDS__Header__Pixel_format<br/>TypeIndex: 145067 (0x246AB)
        [FieldOffset(72)] public global::MioGame.DDS.DDS.Header.Pixel_format pixel_format;
        /// Field: CsEnum DDS__Caps_1<br/>TypeIndex: 145012 (0x24674)
        [FieldOffset(104)] public global::MioGame.DDS.DDS.Caps_1 caps_1;
        /// Field: CsEnum DDS__Caps_2<br/>TypeIndex: 145059 (0x246A3)
        [FieldOffset(108)] public global::MioGame.DDS.DDS.Caps_2 caps_2;
        /// Field: CsArray uint<br/>TypeIndex: 3489 (0x1DA1)
        [FieldOffset(112)] public global::MioGame.InlineArray_CppUInt32_2 cap_34;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(120)] public CppUInt32 reserved_2;
        #endregion
        #region Nested Types
        /// Struct type: DDS::DDS::Header::Pixel_format<br/>TypeIndex: 145067 (0x246AB)<br/>UniqueName: .?AUPixel_format@Header@DDS@2@
        [StructLayout(LayoutKind.Explicit, Size = 32)]
        public partial struct Pixel_format {
            #region Instance Fields
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(0)] public CppUInt32 size;
            /// Field: CsEnum DDS__Pixel_format_flags<br/>TypeIndex: 145014 (0x24676)
            [FieldOffset(4)] public global::MioGame.DDS.DDS.Pixel_format_flags flags;
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(8)] public CppUInt32 fourcc;
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(12)] public CppUInt32 rgb_bit_count;
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(16)] public CppUInt32 r_bitmask;
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(20)] public CppUInt32 g_bitmask;
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(24)] public CppUInt32 b_bitmask;
            /// Field: unsigned (UInt32 | Direct)
            [FieldOffset(28)] public CppUInt32 a_bitmask;
            #endregion
        }
        #endregion
    }
    /// Struct type: DDS::DDS::Header_dx10<br/>TypeIndex: 145065 (0x246A9)<br/>UniqueName: .?AUHeader_dx10@DDS@1@
    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public partial struct Header_dx10 {
        #region Instance Fields
        /// Field: CsEnum DDS__Dxgi_format<br/>TypeIndex: 145063 (0x246A7)
        [FieldOffset(0)] public global::MioGame.DDS.DDS.Dxgi_format dxgi_format;
        /// Field: CsEnum DDS__Resource_type<br/>TypeIndex: 145008 (0x24670)
        [FieldOffset(4)] public global::MioGame.DDS.DDS.Resource_type resource_type;
        /// Field: CsEnum DDS__Dx_misc_flag<br/>TypeIndex: 145006 (0x2466E)
        [FieldOffset(8)] public global::MioGame.DDS.DDS.Dx_misc_flag misc_flags;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(12)] public CppUInt32 array_size;
        /// Field: CsEnum DDS__Dx_alpha_mode<br/>TypeIndex: 145016 (0x24678)
        [FieldOffset(16)] public global::MioGame.DDS.DDS.Dx_alpha_mode alpha_mode;
        #endregion
    }
    /// Struct type: DDS::Export_config<br/>TypeIndex: 92409 (0x178F9)<br/>UniqueName: .?AUExport_config@DDS@@
    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public partial struct Export_config {
        #region Instance Fields
        /// Field: CsStruct String<br/>TypeIndex: 245 (0x10F5)
        [FieldOffset(0)] public global::MioGame.String export_path;
        /// Field: CsEnum Texture_info__Format<br/>TypeIndex: 2433 (0x1981)
        [FieldOffset(16)] public global::MioGame.Texture_info.Format output_fmt;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(20)] public CppUInt32 mip_count;
        #endregion
    }
    /// Enum type: DDS::Storage_format<br/>UniqueName: .?AW4Storage_format@DDS@@
    public enum Storage_format : CppInt32 {
        Unknown = 0,
        DX10 = 1,
    }
    
    /// Enum type: DDS::Dx_misc_flag<br/>UniqueName: .?AW4Dx_misc_flag@DDS@@
    public enum Dx_misc_flag : CppUInt32 {
        Generate_mips = 1,
        Shared = 2,
        Texturecube = 4,
        Drawindirect_args = 16,
        Buffer_allow_raw_views = 32,
        Buffer_structured = 64,
        Resource_clamp = 128,
        Shared_keyedmutex = 256,
        Gdi_compatible = 512,
        Shared_nthandle = 2048,
        Restricted_content = 4096,
        Restrict_shared_resource = 8192,
        Restrict_shared_resource_driver = 16384,
        Guarded = 32768,
        Tile_pool = 131072,
        Tiled = 262144,
    }
    
    /// Enum type: DDS::Resource_type<br/>UniqueName: .?AW4Resource_type@DDS@@
    public enum Resource_type : CppInt32 {
        _1D = 2,
        _2D = 3,
        _3D = 4,
    }
    
    /// Enum type: DDS::Flags<br/>UniqueName: .?AW4Flags@DDS@@
    public enum Flags : CppUInt32 {
        Caps = 1,
        Height = 2,
        Width = 4,
        Pitch = 8,
        Pixel_format = 4096,
        Mipmap_count = 131072,
        Linear_size = 524288,
        Depth = 8388608,
    }
    
    /// Enum type: DDS::Caps_1<br/>UniqueName: .?AW4Caps_1@DDS@@
    public enum Caps_1 : CppUInt32 {
        Complex = 8,
        Mipmap = 4194304,
        Texture = 4096,
    }
    
    /// Enum type: DDS::Pixel_format_flags<br/>UniqueName: .?AW4Pixel_format_flags@DDS@@
    public enum Pixel_format_flags : CppUInt32 {
        Alpha_pixels = 1,
        Alpha = 2,
        Fourcc = 4,
        Rgb = 64,
        Yuv = 512,
        Luminance = 131072,
    }
    
    /// Enum type: DDS::Dx_alpha_mode<br/>UniqueName: .?AW4Dx_alpha_mode@DDS@@
    public enum Dx_alpha_mode : CppUInt32 {
        Unknown = 0,
        Straight = 1,
        Premultiplied = 2,
        Opaque = 3,
        Custom = 4,
    }
    
    /// Enum type: DDS::Caps_2<br/>UniqueName: .?AW4Caps_2@DDS@@
    public enum Caps_2 : CppUInt32 {
        Cubemap = 512,
        Cubemap_xp = 1024,
        Cubemap_xn = 2048,
        Cubemap_yp = 4096,
        Cubemap_yn = 8192,
        Cubemap_zp = 16384,
        Cubemap_zn = 32768,
        Volume = 2097152,
    }
    
    /// Enum type: DDS::Dxgi_format<br/>UniqueName: .?AW4Dxgi_format@DDS@@
    public enum Dxgi_format : CppUInt32 {
        Unknown = 0,
        R32G32B32A32_TYPELESS = 1,
        R32G32B32A32_FLOAT = 2,
        R32G32B32A32_UINT = 3,
        R32G32B32A32_SINT = 4,
        R32G32B32_TYPELESS = 5,
        R32G32B32_FLOAT = 6,
        R32G32B32_UINT = 7,
        R32G32B32_SINT = 8,
        R16G16B16A16_TYPELESS = 9,
        R16G16B16A16_FLOAT = 10,
        R16G16B16A16_UNORM = 11,
        R16G16B16A16_UINT = 12,
        R16G16B16A16_SNORM = 13,
        R16G16B16A16_SINT = 14,
        R32G32_TYPELESS = 15,
        R32G32_FLOAT = 16,
        R32G32_UINT = 17,
        R32G32_SINT = 18,
        R32G8X24_TYPELESS = 19,
        D32_FLOAT_S8X24_UINT = 20,
        R32_FLOAT_X8X24_TYPELESS = 21,
        X32_TYPELESS_G8X24_UINT = 22,
        R10G10B10A2_TYPELESS = 23,
        R10G10B10A2_UNORM = 24,
        R10G10B10A2_UINT = 25,
        R11G11B10_FLOAT = 26,
        R8G8B8A8_TYPELESS = 27,
        R8G8B8A8_UNORM = 28,
        R8G8B8A8_UNORM_SRGB = 29,
        R8G8B8A8_UINT = 30,
        R8G8B8A8_SNORM = 31,
        R8G8B8A8_SINT = 32,
        R16G16_TYPELESS = 33,
        R16G16_FLOAT = 34,
        R16G16_UNORM = 35,
        R16G16_UINT = 36,
        R16G16_SNORM = 37,
        R16G16_SINT = 38,
        R32_TYPELESS = 39,
        D32_FLOAT = 40,
        R32_FLOAT = 41,
        R32_UINT = 42,
        R32_SINT = 43,
        R24G8_TYPELESS = 44,
        D24_UNORM_S8_UINT = 45,
        R24_UNORM_X8_TYPELESS = 46,
        X24_TYPELESS_G8_UINT = 47,
        R8G8_TYPELESS = 48,
        R8G8_UNORM = 49,
        R8G8_UINT = 50,
        R8G8_SNORM = 51,
        R8G8_SINT = 52,
        R16_TYPELESS = 53,
        R16_FLOAT = 54,
        D16_UNORM = 55,
        R16_UNORM = 56,
        R16_UINT = 57,
        R16_SNORM = 58,
        R16_SINT = 59,
        R8_TYPELESS = 60,
        R8_UNORM = 61,
        R8_UINT = 62,
        R8_SNORM = 63,
        R8_SINT = 64,
        A8_UNORM = 65,
        R1_UNORM = 66,
        R9G9B9E5_SHAREDEXP = 67,
        R8G8_B8G8_UNORM = 68,
        G8R8_G8B8_UNORM = 69,
        BC1_TYPELESS = 70,
        BC1_UNORM = 71,
        BC1_UNORM_SRGB = 72,
        BC2_TYPELESS = 73,
        BC2_UNORM = 74,
        BC2_UNORM_SRGB = 75,
        BC3_TYPELESS = 76,
        BC3_UNORM = 77,
        BC3_UNORM_SRGB = 78,
        BC4_TYPELESS = 79,
        BC4_UNORM = 80,
        BC4_SNORM = 81,
        BC5_TYPELESS = 82,
        BC5_UNORM = 83,
        BC5_SNORM = 84,
        B5G6R5_UNORM = 85,
        B5G5R5A1_UNORM = 86,
        B8G8R8A8_UNORM = 87,
        B8G8R8X8_UNORM = 88,
        R10G10B10_XR_BIAS_A2_UNORM = 89,
        B8G8R8A8_TYPELESS = 90,
        B8G8R8A8_UNORM_SRGB = 91,
        B8G8R8X8_TYPELESS = 92,
        B8G8R8X8_UNORM_SRGB = 93,
        BC6H_TYPELESS = 94,
        BC6H_UF16 = 95,
        BC6H_SF16 = 96,
        BC7_TYPELESS = 97,
        BC7_UNORM = 98,
        BC7_UNORM_SRGB = 99,
        AYUV = 100,
        Y410 = 101,
        Y416 = 102,
        NV12 = 103,
        P010 = 104,
        P016 = 105,
        _420_OPAQUE = 106,
        YUY2 = 107,
        Y210 = 108,
        Y216 = 109,
        NV11 = 110,
        AI44 = 111,
        IA44 = 112,
        P8 = 113,
        A8P8 = 114,
        B4G4R4A4_UNORM = 115,
        P208 = 130,
        V208 = 131,
        V408 = 132,
    }
    
    #endregion
}
