// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.EXR;

/// Struct type: EXR::Channel_info<br/>TypeIndex: 92405 (0x178F5)<br/>UniqueName: .?AUChannel_info@EXR@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct Channel_info {
    #region Instance Fields
    /// Field: CsStruct String<br/>TypeIndex: 245 (0x10F5)
    [FieldOffset(0)] public global::MioGame.String name;
    /// Field: void* (Void | NearPointer64)
    [FieldOffset(16)] public void* data;
    #endregion
    #region Nested Types
    /// Enum type: EXR::Channel_info::Format<br/>UniqueName: .?AW4Format@Channel_info@EXR@@
    public enum Format : CppInt32 {
        F32 = 0,
    }
    
    #endregion
}
/// Struct type: EXR::Image_info<br/>TypeIndex: 92411 (0x178FB)<br/>UniqueName: .?AUImage_info@EXR@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct Image_info {
    #region Instance Fields
    /// Field: CsStruct Vec&lt;int,2&gt;<br/>TypeIndex: 1087 (0x143F)
    [FieldOffset(0)] public global::MioGame.Vec_int_2 dim;
    /// Field: CsStruct Array&lt;EXR__Channel_info&gt;<br/>TypeIndex: 92401 (0x178F1)
    [FieldOffset(8)] public global::MioGame.Array_EXR__Channel_info channels;
    #endregion
}
