// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.ImStb;

/// Struct type: ImStb::STB_TexteditState<br/>TypeIndex: 106478 (0x1AFEE)<br/>UniqueName: .?AUSTB_TexteditState@ImStb@@
[StructLayout(LayoutKind.Explicit, Size = 3628)]
public partial struct STB_TexteditState {
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 cursor;
    /// Field: int (Int32 | Direct)
    [FieldOffset(4)] public CppInt32 select_start;
    /// Field: int (Int32 | Direct)
    [FieldOffset(8)] public CppInt32 select_end;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(12)] public CppUnsignedChar insert_mode;
    /// Field: int (Int32 | Direct)
    [FieldOffset(16)] public CppInt32 row_count_per_page;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(20)] public CppUnsignedChar cursor_at_end_of_line;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(21)] public CppUnsignedChar initialized;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(22)] public CppUnsignedChar has_preferred_x;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(23)] public CppUnsignedChar single_line;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(24)] public CppUnsignedChar padding1;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(25)] public CppUnsignedChar padding2;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(26)] public CppUnsignedChar padding3;
    /// Field: float (Float32 | Direct)
    [FieldOffset(28)] public float preferred_x;
    /// Field: CsStruct ImStb__StbUndoState<br/>TypeIndex: 106490 (0x1AFFA)
    [FieldOffset(32)] public global::MioGame.ImStb.StbUndoState undostate;
    #endregion
}
/// Struct type: ImStb::StbFindState<br/>TypeIndex: 106782 (0x1B11E)<br/>UniqueName: .?AUStbFindState@ImStb@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct StbFindState {
    #region Instance Fields
    /// Field: float (Float32 | Direct)
    [FieldOffset(0)] public float x;
    /// Field: float (Float32 | Direct)
    [FieldOffset(4)] public float y;
    /// Field: float (Float32 | Direct)
    [FieldOffset(8)] public float height;
    /// Field: int (Int32 | Direct)
    [FieldOffset(12)] public CppInt32 first_char;
    /// Field: int (Int32 | Direct)
    [FieldOffset(16)] public CppInt32 length;
    /// Field: int (Int32 | Direct)
    [FieldOffset(20)] public CppInt32 prev_first;
    #endregion
}
/// Struct type: ImStb::StbTexteditRow<br/>TypeIndex: 106545 (0x1B031)<br/>UniqueName: .?AUStbTexteditRow@ImStb@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct StbTexteditRow {
    #region Instance Fields
    /// Field: float (Float32 | Direct)
    [FieldOffset(0)] public float x0;
    /// Field: float (Float32 | Direct)
    [FieldOffset(4)] public float x1;
    /// Field: float (Float32 | Direct)
    [FieldOffset(8)] public float baseline_y_delta;
    /// Field: float (Float32 | Direct)
    [FieldOffset(12)] public float ymin;
    /// Field: float (Float32 | Direct)
    [FieldOffset(16)] public float ymax;
    /// Field: int (Int32 | Direct)
    [FieldOffset(20)] public CppInt32 num_chars;
    #endregion
}
/// Struct type: ImStb::StbUndoRecord<br/>TypeIndex: 106497 (0x1B001)<br/>UniqueName: .?AUStbUndoRecord@ImStb@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct StbUndoRecord {
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 where;
    /// Field: int (Int32 | Direct)
    [FieldOffset(4)] public CppInt32 insert_length;
    /// Field: int (Int32 | Direct)
    [FieldOffset(8)] public CppInt32 delete_length;
    /// Field: int (Int32 | Direct)
    [FieldOffset(12)] public CppInt32 char_storage;
    #endregion
}
/// Struct type: ImStb::StbUndoState<br/>TypeIndex: 106490 (0x1AFFA)<br/>UniqueName: .?AUStbUndoState@ImStb@@
[StructLayout(LayoutKind.Explicit, Size = 3596)]
public partial struct StbUndoState {
    #region Instance Fields
    /// Field: CsArray ImStb__StbUndoRecord<br/>TypeIndex: 106484 (0x1AFF4)
    [FieldOffset(0)] public global::MioGame.InlineArray_ImStb_StbUndoRecord_99 undo_rec;
    /// Field: CsArray ushort<br/>TypeIndex: 106486 (0x1AFF6)
    [FieldOffset(1584)] public global::MioGame.InlineArray_CppUInt16Short_999 undo_char;
    /// Field: short (Int16Short | Direct)
    [FieldOffset(3582)] public CppInt16Short undo_point;
    /// Field: short (Int16Short | Direct)
    [FieldOffset(3584)] public CppInt16Short redo_point;
    /// Field: int (Int32 | Direct)
    [FieldOffset(3588)] public CppInt32 undo_char_point;
    /// Field: int (Int32 | Direct)
    [FieldOffset(3592)] public CppInt32 redo_char_point;
    #endregion
}
