// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.Json;

/// Struct type: Json::CharReader<br/>TypeIndex: 189645 (0x2F4CD)<br/>UniqueName: .?AVCharReader@Json@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct CharReader {
    #region Nested Types
    /// Struct type: Json::CharReader::Factory<br/>TypeIndex: 189673 (0x2F4E9)<br/>UniqueName: .?AVFactory@CharReader@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public partial struct Factory {
    }
    #endregion
}
/// Struct type: Json::CharReaderBuilder<br/>TypeIndex: 166887 (0x29BE7)<br/>UniqueName: .?AVCharReaderBuilder@Json@@
[StructLayout(LayoutKind.Explicit, Size = 48)]
public partial struct CharReaderBuilder {
    #region Base Classes
    /// Base class: Json::CharReader::Factory<br/>TypeIndex: 189673 (0x2F4E9)
    [FieldOffset(0)] public global::MioGame.Json.CharReader.Factory Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct Json__Value<br/>TypeIndex: 162327 (0x28A17)
    [FieldOffset(8)] public global::MioGame.Json.Value settings_;
    #endregion
}
/// Enum type: Json::CommentPlacement<br/>UniqueName: .?AW4CommentPlacement@Json@@
public enum CommentPlacement : CppInt32 {
    commentBefore = 0,
    commentAfterOnSameLine = 1,
    commentAfter = 2,
    numberOfCommentPlacement = 3,
}

/// Struct type: Json::Exception<br/>TypeIndex: 189587 (0x2F493)<br/>UniqueName: .?AVException@Json@@
[StructLayout(LayoutKind.Explicit, Size = 56)]
public partial struct Exception {
    #region Base Classes
    /// Base class: std::exception<br/>TypeIndex: 5032 (0x23A8)
    [FieldOffset(0)] public global::MioGame.std.exception Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(24)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char msg_;
    #endregion
}
/// Struct type: Json::FastWriter<br/>TypeIndex: 189414 (0x2F3E6)<br/>UniqueName: .?AVFastWriter@Json@@
[StructLayout(LayoutKind.Explicit, Size = 48)]
public partial struct FastWriter {
    #region Base Classes
    /// Base class: Json::Writer<br/>TypeIndex: 190174 (0x2F6DE)
    [FieldOffset(0)] public global::MioGame.Json.Writer Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(8)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char document_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(40)] public bool yamlCompatibilityEnabled_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(41)] public bool dropNullPlaceholders_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(42)] public bool omitEndingLineFeed_;
    #endregion
}
/// Struct type: Json::Features<br/>TypeIndex: 189687 (0x2F4F7)<br/>UniqueName: .?AVFeatures@Json@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct Features {
    #region Instance Fields
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(0)] public bool allowComments_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(1)] public bool strictRoot_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(2)] public bool allowDroppedNullPlaceholders_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(3)] public bool allowNumericKeys_;
    #endregion
}
/// Struct type: Json::LogicError<br/>TypeIndex: 189441 (0x2F401)<br/>UniqueName: .?AVLogicError@Json@@
[StructLayout(LayoutKind.Explicit, Size = 56)]
public partial struct LogicError {
    #region Base Classes
    /// Base class: Json::Exception<br/>TypeIndex: 189587 (0x2F493)
    [FieldOffset(0)] public global::MioGame.Json.Exception Base;
    #endregion
}
/// Struct type: Json::Path<br/>TypeIndex: 189853 (0x2F59D)<br/>UniqueName: .?AVPath@Json@@
[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct Path {
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;Json__PathArgument,std__allocator&lt;Json__PathArgument&gt; &gt;<br/>TypeIndex: 175485 (0x2BD7D)
    [FieldOffset(0)] public global::MioGame.std.vector_Json__PathArgument_std__allocator_Json__PathArgument args_;
    #endregion
}
/// Struct type: Json::PathArgument<br/>TypeIndex: 189727 (0x2F51F)<br/>UniqueName: .?AVPathArgument@Json@@
[StructLayout(LayoutKind.Explicit, Size = 40)]
public partial struct PathArgument {
    #region Instance Fields
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(0)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char key_;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(32)] public CppUInt32 index_;
    /// Field: CsEnum Json__PathArgument__Kind<br/>TypeIndex: 189710 (0x2F50E)
    [FieldOffset(36)] public global::MioGame.Json.PathArgument.Kind kind_;
    #endregion
    #region Nested Types
    /// Enum type: Json::PathArgument::Kind<br/>UniqueName: .?AW4Kind@PathArgument@Json@@
    public enum Kind : CppInt32 {
        kindNone = 0,
        kindIndex = 1,
        kindKey = 2,
    }
    
    #endregion
}
/// Enum type: Json::PrecisionType<br/>UniqueName: .?AW4PrecisionType@Json@@
public enum PrecisionType : CppInt32 {
    significantDigits = 0,
    decimalPlaces = 1,
}

/// Struct type: Json::Reader<br/>TypeIndex: 189993 (0x2F629)<br/>UniqueName: .?AVReader@Json@@
[StructLayout(LayoutKind.Explicit, Size = 192)]
public unsafe partial struct Reader {
    #region Instance Fields
    /// Field: CsStruct std__stack&lt;Json__Value *,std__deque&lt;Json__Value *,std__allocator&lt;Json__Value *&gt; &gt; &gt;<br/>TypeIndex: 182318 (0x2D82E)
    [FieldOffset(0)] public global::MioGame.std.stack_Json__Value_Ptr_std__deque_Json__Value_Ptr_std__allocator_Json__Value_Ptr nodes_;
    /// Field: CsStruct std__deque&lt;Json__Reader__ErrorInfo,std__allocator&lt;Json__Reader__ErrorInfo&gt; &gt;<br/>TypeIndex: 177452 (0x2C52C)
    [FieldOffset(40)] public global::MioGame.std.deque_Json__Reader__ErrorInfo_std__allocator_Json__Reader__ErrorInfo errors_;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(80)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char document_;
    /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
    [FieldOffset(112)] public CppChar* begin_;
    /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
    [FieldOffset(120)] public CppChar* end_;
    /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
    [FieldOffset(128)] public CppChar* current_;
    /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
    [FieldOffset(136)] public CppChar* lastValueEnd_;
    /// Field: CsPointerType Json__Value*<br/>TypeIndex: 162256 (0x289D0)
    [FieldOffset(144)] public global::MioGame.Json.Value* lastValue_;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(152)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char commentsBefore_;
    /// Field: CsStruct Json__Features<br/>TypeIndex: 189687 (0x2F4F7)
    [FieldOffset(184)] public global::MioGame.Json.Features features_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(188)] public bool collectComments_;
    #endregion
    #region Nested Types
    /// Struct type: Json::Reader::StructuredError<br/>TypeIndex: 190067 (0x2F673)<br/>UniqueName: .?AUStructuredError@Reader@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public partial struct StructuredError {
        #region Instance Fields
        /// Field: __int64 (Int64Quad | Direct)
        [FieldOffset(0)] public CppInt64Quad offset_start;
        /// Field: __int64 (Int64Quad | Direct)
        [FieldOffset(8)] public CppInt64Quad offset_limit;
        /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
        [FieldOffset(16)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char message;
        #endregion
    }
    /// Enum type: Json::Reader::TokenType<br/>UniqueName: .?AW4TokenType@Reader@Json@@
    public enum TokenType : CppInt32 {
        tokenEndOfStream = 0,
        tokenObjectBegin = 1,
        tokenObjectEnd = 2,
        tokenArrayBegin = 3,
        tokenArrayEnd = 4,
        tokenString = 5,
        tokenNumber = 6,
        tokenTrue = 7,
        tokenFalse = 8,
        tokenNull = 9,
        tokenArraySeparator = 10,
        tokenMemberSeparator = 11,
        tokenComment = 12,
        tokenError = 13,
    }
    
    /// Struct type: Json::Reader::Token<br/>TypeIndex: 190027 (0x2F64B)<br/>UniqueName: .?AVToken@Reader@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public unsafe partial struct Token {
        #region Instance Fields
        /// Field: CsEnum Json__Reader__TokenType<br/>TypeIndex: 189923 (0x2F5E3)
        [FieldOffset(0)] public global::MioGame.Json.Reader.TokenType type_;
        /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
        [FieldOffset(8)] public CppChar* start_;
        /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
        [FieldOffset(16)] public CppChar* end_;
        #endregion
    }
    /// Struct type: Json::Reader::ErrorInfo<br/>TypeIndex: 190018 (0x2F642)<br/>UniqueName: .?AVErrorInfo@Reader@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public unsafe partial struct ErrorInfo {
        #region Instance Fields
        /// Field: CsStruct Json__Reader__Token<br/>TypeIndex: 190027 (0x2F64B)
        [FieldOffset(0)] public global::MioGame.Json.Reader.Token token_;
        /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
        [FieldOffset(24)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char message_;
        /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
        [FieldOffset(56)] public CppChar* extra_;
        #endregion
    }
    #endregion
}
/// Struct type: Json::RuntimeError<br/>TypeIndex: 189623 (0x2F4B7)<br/>UniqueName: .?AVRuntimeError@Json@@
[StructLayout(LayoutKind.Explicit, Size = 56)]
public partial struct RuntimeError {
    #region Base Classes
    /// Base class: Json::Exception<br/>TypeIndex: 189587 (0x2F493)
    [FieldOffset(0)] public global::MioGame.Json.Exception Base;
    #endregion
}
/// Struct type: Json::StaticString<br/>TypeIndex: 189806 (0x2F56E)<br/>UniqueName: .?AVStaticString@Json@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct StaticString {
    #region Instance Fields
    /// Field: CsPointerType sbyte*<br/>TypeIndex: 36 (0x1024)
    [FieldOffset(0)] public CppChar* c_str_;
    #endregion
}
/// Struct type: Json::StreamWriter<br/>TypeIndex: 189515 (0x2F44B)<br/>UniqueName: .?AVStreamWriter@Json@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct StreamWriter {
    #region Instance Fields
    /// Field: CsPointerType std__basic_ostream&lt;char,std__char_traits&lt;char&gt; &gt;*<br/>TypeIndex: 179414 (0x2CCD6)
    [FieldOffset(8)] public global::MioGame.std.basic_ostream_char_std__char_traits_char* sout_;
    #endregion
    #region Nested Types
    /// Struct type: Json::StreamWriter::Factory<br/>TypeIndex: 189548 (0x2F46C)<br/>UniqueName: .?AVFactory@StreamWriter@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public partial struct Factory {
    }
    #endregion
}
/// Struct type: Json::StreamWriterBuilder<br/>TypeIndex: 189391 (0x2F3CF)<br/>UniqueName: .?AVStreamWriterBuilder@Json@@
[StructLayout(LayoutKind.Explicit, Size = 48)]
public partial struct StreamWriterBuilder {
    #region Base Classes
    /// Base class: Json::StreamWriter::Factory<br/>TypeIndex: 189548 (0x2F46C)
    [FieldOffset(0)] public global::MioGame.Json.StreamWriter.Factory Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct Json__Value<br/>TypeIndex: 162327 (0x28A17)
    [FieldOffset(8)] public global::MioGame.Json.Value settings_;
    #endregion
}
/// Struct type: Json::StyledStreamWriter<br/>TypeIndex: 190152 (0x2F6C8)<br/>UniqueName: .?AVStyledStreamWriter@Json@@
[StructLayout(LayoutKind.Explicit, Size = 112)]
public unsafe partial struct StyledStreamWriter {
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__allocator&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt; &gt;<br/>TypeIndex: 4268 (0x20AC)
    [FieldOffset(0)] public global::MioGame.std.vector_std__basic_string_char_std__char_traits_char_std__allocator_char_std__allocator_std__basic_string_char_std__char_traits_char_std__allocator_char childValues_;
    /// Field: CsPointerType std__basic_ostream&lt;char,std__char_traits&lt;char&gt; &gt;*<br/>TypeIndex: 179414 (0x2CCD6)
    [FieldOffset(24)] public global::MioGame.std.basic_ostream_char_std__char_traits_char* document_;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(32)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char indentString_;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(64)] public CppUInt32 rightMargin_;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(72)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char indentation_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(104)] public bool addChildValues_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(104)] public bool indented_;
    #endregion
}
/// Struct type: Json::StyledWriter<br/>TypeIndex: 190195 (0x2F6F3)<br/>UniqueName: .?AVStyledWriter@Json@@
[StructLayout(LayoutKind.Explicit, Size = 112)]
public partial struct StyledWriter {
    #region Base Classes
    /// Base class: Json::Writer<br/>TypeIndex: 190174 (0x2F6DE)
    [FieldOffset(0)] public global::MioGame.Json.Writer Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__allocator&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt; &gt;<br/>TypeIndex: 4268 (0x20AC)
    [FieldOffset(8)] public global::MioGame.std.vector_std__basic_string_char_std__char_traits_char_std__allocator_char_std__allocator_std__basic_string_char_std__char_traits_char_std__allocator_char childValues_;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(32)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char document_;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(64)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char indentString_;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(96)] public CppUInt32 rightMargin_;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(100)] public CppUInt32 indentSize_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(104)] public bool addChildValues_;
    #endregion
}
/// Struct type: Json::Value<br/>TypeIndex: 162327 (0x28A17)<br/>UniqueName: .?AVValue@Json@@
[StructLayout(LayoutKind.Explicit, Size = 40)]
public unsafe partial struct Value {
    #region Static Fields
    /// Field: Json__Value&amp;<br/>TypeIndex 114507 (0x1CF4B)
    public static unsafe ref global::MioGame.Json.Value* @null => ref *((global::MioGame.Json.Value**)(MioGameMemoryAddress + 18137952));
    /// Field: Json__Value&amp;<br/>TypeIndex 114507 (0x1CF4B)
    /// Field: TypeIndex __int64 (Int64Quad | Direct)
    /// Field: TypeIndex __int64 (Int64Quad | Direct)
    /// Field: TypeIndex unsigned __int64 (UInt64Quad | Direct)
    /// Field: TypeIndex int (Int32 | Direct)
    /// Field: TypeIndex int (Int32 | Direct)
    /// Field: TypeIndex unsigned (UInt32 | Direct)
    /// Field: TypeIndex __int64 (Int64Quad | Direct)
    /// Field: TypeIndex __int64 (Int64Quad | Direct)
    /// Field: TypeIndex unsigned __int64 (UInt64Quad | Direct)
    /// Field: TypeIndex unsigned (UInt32 | Direct)
    #endregion
    #region Instance Fields
    /// Field: CsUnion Json__Value__ValueHolder<br/>TypeIndex: 189735 (0x2F527)
    [FieldOffset(0)] public global::MioGame.Json.Value.ValueHolder value_;
    /// Field: CsEnum Json__ValueType<br/>TypeIndex: 114284 (0x1CE6C)
    [FieldOffset(8)] public global::MioGame.Json.ValueType type_;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(8)] public CppUInt32 allocated_;
    /// Field: CsPointerType Json__Value__CommentInfo*<br/>TypeIndex: 162313 (0x28A09)
    [FieldOffset(16)] public global::MioGame.Json.Value.CommentInfo* comments_;
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(24)] public CppInt64Quad start_;
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(32)] public CppInt64Quad limit_;
    #endregion
    #region Nested Types
    /// Struct type: Json::Value::CommentInfo<br/>TypeIndex: 189750 (0x2F536)<br/>UniqueName: .?AUCommentInfo@Value@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct CommentInfo {
        #region Instance Fields
        /// Field: char* (NarrowCharacter | NearPointer64)
        [FieldOffset(0)] public CppChar* comment_;
        #endregion
    }
    /// Struct type: Json::Value::ValueHolder<br/>TypeIndex: 189735 (0x2F527)<br/>UniqueName: .?ATValueHolder@Value@Json@@
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct ValueHolder {
        #region Instance Fields
        /// Field: __int64 (Int64Quad | Direct)
        [FieldOffset(0)] public CppInt64Quad int_;
        /// Field: unsigned __int64 (UInt64Quad | Direct)
        [FieldOffset(0)] public CppUInt64Quad uint_;
        /// Field: double (Float64 | Direct)
        [FieldOffset(0)] public double real_;
        /// Field: bool (Boolean8 | Direct)
        [FieldOffset(0)] public bool bool_;
        /// Field: char* (NarrowCharacter | NearPointer64)
        [FieldOffset(0)] public CppChar* string_;
        /// Field: CsPointerType std__map&lt;Json__Value__CZString,Json__Value,std__less&lt;Json__Value__CZString&gt;,std__allocator&lt;std__pair&lt;Json__Value__CZString const ,Json__Value&gt; &gt; &gt;*<br/>TypeIndex: 189730 (0x2F522)
        [FieldOffset(0)] public global::MioGame.std.map_Json__Value__CZString_Json__Value_std__less_Json__Value__CZString_std__allocator_std__pair_Json__Value__CZString_const_Json__Value* map_;
        #endregion
    }
    #endregion
}
/// Struct type: Json::ValueConstIterator<br/>TypeIndex: 156409 (0x272F9)<br/>UniqueName: .?AVValueConstIterator@Json@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct ValueConstIterator {
    #region Base Classes
    /// Base class: Json::ValueIteratorBase<br/>TypeIndex: 189475 (0x2F423)
    [FieldOffset(0)] public global::MioGame.Json.ValueIteratorBase Base;
    #endregion
}
/// Struct type: Json::ValueIterator<br/>TypeIndex: 190103 (0x2F697)<br/>UniqueName: .?AVValueIterator@Json@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct ValueIterator {
    #region Base Classes
    /// Base class: Json::ValueIteratorBase<br/>TypeIndex: 189475 (0x2F423)
    [FieldOffset(0)] public global::MioGame.Json.ValueIteratorBase Base;
    #endregion
}
/// Struct type: Json::ValueIteratorBase<br/>TypeIndex: 189475 (0x2F423)<br/>UniqueName: .?AVValueIteratorBase@Json@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct ValueIteratorBase {
    #region Instance Fields
    /// Field: CsStruct std___Tree_iterator&lt;std___Tree_val&lt;std___Tree_simple_types&lt;std__pair&lt;Json__Value__CZString const ,Json__Value&gt; &gt; &gt; &gt;<br/>TypeIndex: 179554 (0x2CD62)
    [FieldOffset(0)] public global::MioGame.std._Tree_iterator_std___Tree_val_std___Tree_simple_types_std__pair_Json__Value__CZString_const_Json__Value current_;
    /// Field: bool (Boolean8 | Direct)
    [FieldOffset(8)] public bool isNull_;
    #endregion
}
/// Enum type: Json::ValueType<br/>UniqueName: .?AW4ValueType@Json@@
public enum ValueType : CppInt32 {
    nullValue = 0,
    intValue = 1,
    uintValue = 2,
    realValue = 3,
    stringValue = 4,
    booleanValue = 5,
    arrayValue = 6,
    objectValue = 7,
}

/// Struct type: Json::Writer<br/>TypeIndex: 190174 (0x2F6DE)<br/>UniqueName: .?AVWriter@Json@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct Writer {
}
