// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.nvtt;

/// Enum type: nvtt::Container<br/>UniqueName: .?AW4Container@nvtt@@
public enum Container : CppInt32 {
    Container_DDS = 0,
    Container_DDS10 = 1,
}

/// Enum type: nvtt::Format<br/>UniqueName: .?AW4Format@nvtt@@
public enum Format : CppInt32 {
    Format_RGB = 0,
    Format_RGBA = 0,
    Format_DXT1 = 1,
    Format_DXT1a = 2,
    Format_DXT3 = 3,
    Format_DXT5 = 4,
    Format_DXT5n = 5,
    Format_BC1 = 1,
    Format_BC1a = 2,
    Format_BC2 = 3,
    Format_BC3 = 4,
    Format_BC3n = 5,
    Format_BC4 = 6,
    Format_BC4S = 7,
    Format_ATI2 = 8,
    Format_BC5 = 9,
    Format_BC5S = 10,
    Format_DXT1n = 11,
    Format_CTX1 = 12,
    Format_BC6U = 13,
    Format_BC6S = 14,
    Format_BC7 = 15,
    Format_BC3_RGBM = 16,
    Format_ASTC_LDR_4x4 = 17,
    Format_ASTC_LDR_5x4 = 18,
    Format_ASTC_LDR_5x5 = 19,
    Format_ASTC_LDR_6x5 = 20,
    Format_ASTC_LDR_6x6 = 21,
    Format_ASTC_LDR_8x5 = 22,
    Format_ASTC_LDR_8x6 = 23,
    Format_ASTC_LDR_8x8 = 24,
    Format_ASTC_LDR_10x5 = 25,
    Format_ASTC_LDR_10x6 = 26,
    Format_ASTC_LDR_10x8 = 27,
    Format_ASTC_LDR_10x10 = 28,
    Format_ASTC_LDR_12x10 = 29,
    Format_ASTC_LDR_12x12 = 30,
    Format_Count = 31,
}

/// Enum type: nvtt::InputFormat<br/>UniqueName: .?AW4InputFormat@nvtt@@
public enum InputFormat : CppInt32 {
    InputFormat_BGRA_8UB = 0,
    InputFormat_BGRA_8SB = 1,
    InputFormat_RGBA_16F = 2,
    InputFormat_RGBA_32F = 3,
    InputFormat_R_32F = 4,
}

/// Enum type: nvtt::MipmapFilter<br/>UniqueName: .?AW4MipmapFilter@nvtt@@
public enum MipmapFilter : CppInt32 {
    MipmapFilter_Box = 0,
    MipmapFilter_Triangle = 1,
    MipmapFilter_Kaiser = 2,
}

/// Enum type: nvtt::Quality<br/>UniqueName: .?AW4Quality@nvtt@@
public enum Quality : CppInt32 {
    Quality_Fastest = 0,
    Quality_Normal = 1,
    Quality_Production = 2,
    Quality_Highest = 3,
}

/// Enum type: nvtt::WrapMode<br/>UniqueName: .?AW4WrapMode@nvtt@@
public enum WrapMode : CppInt32 {
    WrapMode_Clamp = 0,
    WrapMode_Repeat = 1,
    WrapMode_Mirror = 2,
}

/// [Forward Reference Only] Struct type: nvtt::CompressionOptions<br/>TypeIndex: 145187 (0x24723)<br/>UniqueName: .?AUCompressionOptions@nvtt@@
 public partial struct CompressionOptions;
/// [Forward Reference Only] Struct type: nvtt::Context<br/>TypeIndex: 145186 (0x24722)<br/>UniqueName: .?AUContext@nvtt@@
 public partial struct Context;
/// [Forward Reference Only] Struct type: nvtt::OutputOptions<br/>TypeIndex: 145188 (0x24724)<br/>UniqueName: .?AUOutputOptions@nvtt@@
 public partial struct OutputOptions;
/// [Forward Reference Only] Struct type: nvtt::Surface<br/>TypeIndex: 145185 (0x24721)<br/>UniqueName: .?AUSurface@nvtt@@
 public partial struct Surface;
