// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.PlayFab.EventsModels;

/// Struct type: PlayFab::EventsModels::EntityKey<br/>TypeIndex: 115014 (0x1D146)<br/>UniqueName: .?AUEntityKey@EventsModels@PlayFab@@
[StructLayout(LayoutKind.Explicit, Size = 72)]
public partial struct EntityKey {
    #region Memory Address Access
    public static class Pointers {
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EntityKey*, void> dtor = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EntityKey*, void>)(MioGameFunctionAddress + 6068256);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EntityKey*, global::MioGame.Json.Value*, void> FromJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EntityKey*, global::MioGame.Json.Value*, void>)(MioGameFunctionAddress + 6068304);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EntityKey*, global::MioGame.Json.Value> ToJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EntityKey*, global::MioGame.Json.Value>)(MioGameFunctionAddress + 6068384);
    }
    #endregion
    #region Base Classes
    /// Base class: PlayFab::PlayFabBaseModel<br/>TypeIndex: 114730 (0x1D02A)
    [FieldOffset(0)] public global::MioGame.PlayFab.PlayFabBaseModel Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(8)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char Id;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(40)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char Type;
    #endregion
    #region Instance Methods
    public unsafe void FromJson(global::MioGame.Json.Value* input) {
        fixed (global::MioGame.PlayFab.EventsModels.EntityKey* pThis = &this) {
            Pointers.FromJson(pThis, input);
        }
    }
    public unsafe global::MioGame.Json.Value ToJson() {
        fixed (global::MioGame.PlayFab.EventsModels.EntityKey* pThis = &this) {
            return Pointers.ToJson(pThis);
        }
    }
    #endregion
}
/// Struct type: PlayFab::EventsModels::EventContents<br/>TypeIndex: 114520 (0x1CF58)<br/>UniqueName: .?AUEventContents@EventsModels@PlayFab@@
[StructLayout(LayoutKind.Explicit, Size = 288)]
public partial struct EventContents {
    #region Memory Address Access
    public static class Pointers {
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EventContents*, void> dtor = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EventContents*, void>)(MioGameFunctionAddress + 6048256);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EventContents*, global::MioGame.Json.Value*, void> FromJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EventContents*, global::MioGame.Json.Value*, void>)(MioGameFunctionAddress + 6066480);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EventContents*, global::MioGame.Json.Value> ToJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.EventContents*, global::MioGame.Json.Value>)(MioGameFunctionAddress + 6066800);
    }
    #endregion
    #region Base Classes
    /// Base class: PlayFab::PlayFabBaseModel<br/>TypeIndex: 114730 (0x1D02A)
    [FieldOffset(0)] public global::MioGame.PlayFab.PlayFabBaseModel Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__map&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__less&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt;,std__allocator&lt;std__pair&lt;const std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt; &gt; &gt;<br/>TypeIndex: 1782 (0x16F6)
    [FieldOffset(8)] public global::MioGame.std.map_std__basic_string_char_std__char_traits_char_std__allocator_char_std__basic_string_char_std__char_traits_char_std__allocator_char_std__less_std__basic_string_char_std__char_traits_char_std__allocator_char_std__allocator_std__pair_const_std__basic_string_char_std__char_traits_char_std__allocator_char_std__basic_string_char_std__char_traits_char_std__allocator_char CustomTags;
    /// Field: CsStruct PlayFab__Boxed&lt;PlayFab__EventsModels__EntityKey&gt;<br/>TypeIndex: 114777 (0x1D059)
    [FieldOffset(24)] public global::MioGame.PlayFab.Boxed_PlayFab__EventsModels__EntityKey Entity;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(104)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char EventNamespace;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(136)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char Name;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(168)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char OriginalId;
    /// Field: CsStruct PlayFab__Boxed&lt;long long&gt;<br/>TypeIndex: 114792 (0x1D068)
    [FieldOffset(200)] public global::MioGame.PlayFab.Boxed_long_long OriginalTimestamp;
    /// Field: CsStruct Json__Value<br/>TypeIndex: 162327 (0x28A17)
    [FieldOffset(216)] public global::MioGame.Json.Value Payload;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(256)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char PayloadJSON;
    #endregion
    #region Instance Methods
    public unsafe void FromJson(global::MioGame.Json.Value* input) {
        fixed (global::MioGame.PlayFab.EventsModels.EventContents* pThis = &this) {
            Pointers.FromJson(pThis, input);
        }
    }
    public unsafe global::MioGame.Json.Value ToJson() {
        fixed (global::MioGame.PlayFab.EventsModels.EventContents* pThis = &this) {
            return Pointers.ToJson(pThis);
        }
    }
    #endregion
}
/// Struct type: PlayFab::EventsModels::WriteEventsRequest<br/>TypeIndex: 116014 (0x1D52E)<br/>UniqueName: .?AUWriteEventsRequest@EventsModels@PlayFab@@
[StructLayout(LayoutKind.Explicit, Size = 56)]
public partial struct WriteEventsRequest {
    #region Memory Address Access
    public static class Pointers {
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsRequest*, void> dtor = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsRequest*, void>)(MioGameFunctionAddress + 6048720);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsRequest*, global::MioGame.Json.Value*, void> FromJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsRequest*, global::MioGame.Json.Value*, void>)(MioGameFunctionAddress + 6064288);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsRequest*, global::MioGame.Json.Value> ToJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsRequest*, global::MioGame.Json.Value>)(MioGameFunctionAddress + 6064368);
    }
    #endregion
    #region Base Classes
    /// Base class: PlayFab::PlayFabRequestCommon<br/>TypeIndex: 115228 (0x1D21C)
    [FieldOffset(0)] public global::MioGame.PlayFab.PlayFabRequestCommon Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__map&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__less&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt;,std__allocator&lt;std__pair&lt;const std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt; &gt; &gt;<br/>TypeIndex: 1782 (0x16F6)
    [FieldOffset(24)] public global::MioGame.std.map_std__basic_string_char_std__char_traits_char_std__allocator_char_std__basic_string_char_std__char_traits_char_std__allocator_char_std__less_std__basic_string_char_std__char_traits_char_std__allocator_char_std__allocator_std__pair_const_std__basic_string_char_std__char_traits_char_std__allocator_char_std__basic_string_char_std__char_traits_char_std__allocator_char CustomTags;
    /// Field: CsStruct std__list&lt;PlayFab__EventsModels__EventContents,std__allocator&lt;PlayFab__EventsModels__EventContents&gt; &gt;<br/>TypeIndex: 116191 (0x1D5DF)
    [FieldOffset(40)] public global::MioGame.std.list_PlayFab__EventsModels__EventContents_std__allocator_PlayFab__EventsModels__EventContents Events;
    #endregion
    #region Instance Methods
    public unsafe void FromJson(global::MioGame.Json.Value* input) {
        fixed (global::MioGame.PlayFab.EventsModels.WriteEventsRequest* pThis = &this) {
            Pointers.FromJson(pThis, input);
        }
    }
    public unsafe global::MioGame.Json.Value ToJson() {
        fixed (global::MioGame.PlayFab.EventsModels.WriteEventsRequest* pThis = &this) {
            return Pointers.ToJson(pThis);
        }
    }
    #endregion
}
/// Struct type: PlayFab::EventsModels::WriteEventsResponse<br/>TypeIndex: 163204 (0x28D84)<br/>UniqueName: .?AUWriteEventsResponse@EventsModels@PlayFab@@
[StructLayout(LayoutKind.Explicit, Size = 64)]
public partial struct WriteEventsResponse {
    #region Memory Address Access
    public static class Pointers {
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsResponse*, void> dtor = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsResponse*, void>)(MioGameFunctionAddress + 14730176);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsResponse*, global::MioGame.Json.Value*, void> FromJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsResponse*, global::MioGame.Json.Value*, void>)(MioGameFunctionAddress + 14730512);
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsResponse*, global::MioGame.Json.Value> ToJson = (delegate* unmanaged[Cdecl]<global::MioGame.PlayFab.EventsModels.WriteEventsResponse*, global::MioGame.Json.Value>)(MioGameFunctionAddress + 14731488);
    }
    #endregion
    #region Base Classes
    /// Base class: PlayFab::PlayFabResultCommon<br/>TypeIndex: 157945 (0x278F9)
    [FieldOffset(0)] public global::MioGame.PlayFab.PlayFabResultCommon Base;
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__list&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;,std__allocator&lt;std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt; &gt; &gt;<br/>TypeIndex: 115522 (0x1D342)
    [FieldOffset(48)] public global::MioGame.std.list_std__basic_string_char_std__char_traits_char_std__allocator_char_std__allocator_std__basic_string_char_std__char_traits_char_std__allocator_char AssignedEventIds;
    #endregion
    #region Instance Methods
    public unsafe void FromJson(global::MioGame.Json.Value* input) {
        fixed (global::MioGame.PlayFab.EventsModels.WriteEventsResponse* pThis = &this) {
            Pointers.FromJson(pThis, input);
        }
    }
    public unsafe global::MioGame.Json.Value ToJson() {
        fixed (global::MioGame.PlayFab.EventsModels.WriteEventsResponse* pThis = &this) {
            return Pointers.ToJson(pThis);
        }
    }
    #endregion
}
