// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.std.chrono;

/// Struct type: std::chrono::duration&lt;__int64,std::ratio&lt;1,1&gt; &gt;<br/>TypeIndex: 186283 (0x2E7AB)<br/>UniqueName: .?AV?$duration@_JU?$ratio@$00$00@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration___int64_std__ratio_1_1 {
    #region Instance Fields
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;__int64,std::ratio&lt;1,1000&gt; &gt;<br/>TypeIndex: 186226 (0x2E772)<br/>UniqueName: .?AV?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration___int64_std__ratio_1_1000 {
    #region Instance Fields
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;__int64,std::ratio&lt;1,1000000&gt; &gt;<br/>TypeIndex: 186433 (0x2E841)<br/>UniqueName: .?AV?$duration@_JU?$ratio@$00$0PECEA@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration___int64_std__ratio_1_1000000 {
    #region Instance Fields
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;__int64,std::ratio&lt;1,10000000&gt; &gt;<br/>TypeIndex: 156012 (0x2716C)<br/>UniqueName: .?AV?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration___int64_std__ratio_1_10000000 {
    #region Instance Fields
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;__int64,std::ratio&lt;1,1000000000&gt; &gt;<br/>TypeIndex: 171377 (0x2AD71)<br/>UniqueName: .?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration___int64_std__ratio_1_1000000000 {
    #region Instance Fields
    /// Field: __int64 (Int64Quad | Direct)
    [FieldOffset(0)] public CppInt64Quad _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;double,std::ratio&lt;1,1&gt; &gt;<br/>TypeIndex: 186613 (0x2E8F5)<br/>UniqueName: .?AV?$duration@NU?$ratio@$00$00@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration_double_std__ratio_1_1 {
    #region Instance Fields
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;double,std::ratio&lt;1,1000&gt; &gt;<br/>TypeIndex: 186588 (0x2E8DC)<br/>UniqueName: .?AV?$duration@NU?$ratio@$00$0DOI@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration_double_std__ratio_1_1000 {
    #region Instance Fields
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;double,std::ratio&lt;1,1000000&gt; &gt;<br/>TypeIndex: 186465 (0x2E861)<br/>UniqueName: .?AV?$duration@NU?$ratio@$00$0PECEA@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration_double_std__ratio_1_1000000 {
    #region Instance Fields
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;double,std::ratio&lt;1,1000000000&gt; &gt;<br/>TypeIndex: 186499 (0x2E883)<br/>UniqueName: .?AV?$duration@NU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration_double_std__ratio_1_1000000000 {
    #region Instance Fields
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;double,std::ratio&lt;3600,1&gt; &gt;<br/>TypeIndex: 186660 (0x2E924)<br/>UniqueName: .?AV?$duration@NU?$ratio@$0OBA@$00@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration_double_std__ratio_3600_1 {
    #region Instance Fields
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;double,std::ratio&lt;60,1&gt; &gt;<br/>TypeIndex: 186394 (0x2E81A)<br/>UniqueName: .?AV?$duration@NU?$ratio@$0DM@$00@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct duration_double_std__ratio_60_1 {
    #region Instance Fields
    /// Field: double (Float64 | Direct)
    [FieldOffset(0)] public double _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;int,std::ratio&lt;3600,1&gt; &gt;<br/>TypeIndex: 186547 (0x2E8B3)<br/>UniqueName: .?AV?$duration@HU?$ratio@$0OBA@$00@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct duration_int_std__ratio_3600_1 {
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration&lt;int,std::ratio&lt;60,1&gt; &gt;<br/>TypeIndex: 186258 (0x2E792)<br/>UniqueName: .?AV?$duration@HU?$ratio@$0DM@$00@std@@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct duration_int_std__ratio_60_1 {
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 _MyRep;
    #endregion
}
/// Struct type: std::chrono::duration_values&lt;__int64&gt;<br/>TypeIndex: 168521 (0x2A249)<br/>UniqueName: .?AU?$duration_values@_J@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct duration_values___int64 {
}
/// Struct type: std::chrono::steady_clock<br/>TypeIndex: 186320 (0x2E7D0)<br/>UniqueName: .?AUsteady_clock@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct steady_clock {
    #region Static Fields
    /// Field: TypeIndex bool (Boolean8 | Direct) Value: 1 (C# Type: UInt16)
    public const bool is_steady = true;
    #endregion
}
/// Struct type: std::chrono::system_clock<br/>TypeIndex: 186344 (0x2E7E8)<br/>UniqueName: .?AUsystem_clock@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct system_clock {
    #region Static Fields
    /// Field: TypeIndex bool (Boolean8 | Direct) Value: 0 (C# Type: UInt16)
    public const bool is_steady = false;
    #endregion
}
/// Struct type: std::chrono::time_point&lt;std::chrono::steady_clock,std::chrono::duration&lt;__int64,std::ratio&lt;1,1000000000&gt; &gt; &gt;<br/>TypeIndex: 186312 (0x2E7C8)<br/>UniqueName: .?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct time_point_std__chrono__steady_clock_std__chrono__duration___int64_std__ratio_1_1000000000 {
    #region Instance Fields
    /// Field: CsStruct std__chrono__duration&lt;__int64,std__ratio&lt;1,1000000000&gt; &gt;<br/>TypeIndex: 171377 (0x2AD71)
    [FieldOffset(0)] public global::MioGame.std.chrono.duration___int64_std__ratio_1_1000000000 _MyDur;
    #endregion
}
/// Struct type: std::chrono::time_point&lt;std::chrono::system_clock,std::chrono::duration&lt;__int64,std::ratio&lt;1,1&gt; &gt; &gt;<br/>TypeIndex: 156030 (0x2717E)<br/>UniqueName: .?AV?$time_point@Usystem_clock@chrono@std@@V?$duration@_JU?$ratio@$00$00@std@@@23@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct time_point_std__chrono__system_clock_std__chrono__duration___int64_std__ratio_1_1 {
    #region Instance Fields
    /// Field: CsStruct std__chrono__duration&lt;__int64,std__ratio&lt;1,1&gt; &gt;<br/>TypeIndex: 186283 (0x2E7AB)
    [FieldOffset(0)] public global::MioGame.std.chrono.duration___int64_std__ratio_1_1 _MyDur;
    #endregion
}
/// Struct type: std::chrono::time_point&lt;std::chrono::system_clock,std::chrono::duration&lt;__int64,std::ratio&lt;1,1000&gt; &gt; &gt;<br/>TypeIndex: 156048 (0x27190)<br/>UniqueName: .?AV?$time_point@Usystem_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DOI@@std@@@23@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct time_point_std__chrono__system_clock_std__chrono__duration___int64_std__ratio_1_1000 {
    #region Instance Fields
    /// Field: CsStruct std__chrono__duration&lt;__int64,std__ratio&lt;1,1000&gt; &gt;<br/>TypeIndex: 186226 (0x2E772)
    [FieldOffset(0)] public global::MioGame.std.chrono.duration___int64_std__ratio_1_1000 _MyDur;
    #endregion
}
/// Struct type: std::chrono::time_point&lt;std::chrono::system_clock,std::chrono::duration&lt;__int64,std::ratio&lt;1,10000000&gt; &gt; &gt;<br/>TypeIndex: 155998 (0x2715E)<br/>UniqueName: .?AV?$time_point@Usystem_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0JIJGIA@@std@@@23@@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct time_point_std__chrono__system_clock_std__chrono__duration___int64_std__ratio_1_10000000 {
    #region Instance Fields
    /// Field: CsStruct std__chrono__duration&lt;__int64,std__ratio&lt;1,10000000&gt; &gt;<br/>TypeIndex: 156012 (0x2716C)
    [FieldOffset(0)] public global::MioGame.std.chrono.duration___int64_std__ratio_1_10000000 _MyDur;
    #endregion
}
/// Struct type: std::chrono::treat_as_floating_point&lt;__int64&gt;<br/>TypeIndex: 186400 (0x2E820)<br/>UniqueName: .?AU?$treat_as_floating_point@_J@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct treat_as_floating_point___int64 {
    #region Base Classes
    /// Base class: std::is_floating_point&lt;__int64&gt;<br/>TypeIndex: 180183 (0x2CFD7)
    [FieldOffset(0)] public global::MioGame.std.is_floating_point___int64 Base;
    #endregion
}
/// Struct type: std::chrono::treat_as_floating_point&lt;double&gt;<br/>TypeIndex: 186209 (0x2E761)<br/>UniqueName: .?AU?$treat_as_floating_point@N@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct treat_as_floating_point_double {
    #region Base Classes
    /// Base class: std::is_floating_point&lt;double&gt;<br/>TypeIndex: 174656 (0x2BA40)
    [FieldOffset(0)] public global::MioGame.std.is_floating_point_double Base;
    #endregion
}
/// Struct type: std::chrono::treat_as_floating_point&lt;int&gt;<br/>TypeIndex: 186327 (0x2E7D7)<br/>UniqueName: .?AU?$treat_as_floating_point@H@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct treat_as_floating_point_int {
    #region Base Classes
    /// Base class: std::is_floating_point&lt;int&gt;<br/>TypeIndex: 186942 (0x2EA3E)
    [FieldOffset(0)] public global::MioGame.std.is_floating_point_int Base;
    #endregion
}
/// Struct type: std::chrono::treat_as_floating_point&lt;long double&gt;<br/>TypeIndex: 186594 (0x2E8E2)<br/>UniqueName: .?AU?$treat_as_floating_point@O@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct treat_as_floating_point_long_double {
    #region Base Classes
    /// Base class: std::is_floating_point&lt;long double&gt;<br/>TypeIndex: 187777 (0x2ED81)
    [FieldOffset(0)] public global::MioGame.std.is_floating_point_long_double Base;
    #endregion
}
/// Struct type: std::chrono::treat_as_floating_point&lt;unsigned __int64&gt;<br/>TypeIndex: 186619 (0x2E8FB)<br/>UniqueName: .?AU?$treat_as_floating_point@_K@chrono@std@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct treat_as_floating_point_unsigned___int64 {
    #region Base Classes
    /// Base class: std::is_floating_point&lt;unsigned __int64&gt;<br/>TypeIndex: 183742 (0x2DDBE)
    [FieldOffset(0)] public global::MioGame.std.is_floating_point_unsigned___int64 Base;
    #endregion
}
