// <auto-generated>
// This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Runtime.InteropServices;
using System.CodeDom.Compiler;

using CppHResult = uint;

// 1 byte char values
using CppUnsignedChar = byte;
using CppChar = sbyte;
using CppSignedChar = sbyte;

// 2 byte char values
using CppChar16 = ushort;
using CppWideChar = ushort;

// 4 byte char values
using CppChar32 = uint;

using CppInt8 = sbyte;
using CppUInt8 = byte;

// 2 byte integer values
using CppInt16 = short;
using CppUInt16 = ushort;
using CppInt16Short = short;
using CppUInt16Short = ushort;

// 4 byte integer values
using CppInt32 = int;
using CppUInt32 = uint;
using CppInt32Long = int;
using CppUInt32Long = uint;

// 8 byte integer values
using CppInt64 = long;
using CppUInt64 = ulong;
using CppInt64Quad = long;
using CppUInt64Quad = ulong;

// 16 byte integer values
using CppInt128 = System.Int128;
using CppUInt128 = System.UInt128;
using CppInt128Oct = System.Int128;
using CppUInt128Oct = System.UInt128;

// 4 byte float values
using CppFloat32PartialPrecision = float;

// complex float values
using CppComplex128 = System.Numerics.Complex;

// boolean values
using CppBoolean16 = ushort;
using CppBoolean32 = uint;
using CppBoolean64 = ulong;
using CppBoolean128 = System.UInt128;

using static MioGame.MioGameModule;
namespace MioGame.tinyexr;

/// Struct type: tinyexr::Box2iInfo<br/>TypeIndex: 145889 (0x249E1)<br/>UniqueName: .?AUBox2iInfo@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public partial struct Box2iInfo {
    #region Instance Fields
    /// Field: int (Int32 | Direct)
    [FieldOffset(0)] public CppInt32 min_x;
    /// Field: int (Int32 | Direct)
    [FieldOffset(4)] public CppInt32 min_y;
    /// Field: int (Int32 | Direct)
    [FieldOffset(8)] public CppInt32 max_x;
    /// Field: int (Int32 | Direct)
    [FieldOffset(12)] public CppInt32 max_y;
    #endregion
}
/// Struct type: tinyexr::ChannelInfo<br/>TypeIndex: 146256 (0x24B50)<br/>UniqueName: .?AUChannelInfo@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 56)]
public partial struct ChannelInfo {
    #region Instance Fields
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(0)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char name;
    /// Field: int (Int32 | Direct)
    [FieldOffset(32)] public CppInt32 pixel_type;
    /// Field: int (Int32 | Direct)
    [FieldOffset(36)] public CppInt32 requested_pixel_type;
    /// Field: int (Int32 | Direct)
    [FieldOffset(40)] public CppInt32 x_sampling;
    /// Field: int (Int32 | Direct)
    [FieldOffset(44)] public CppInt32 y_sampling;
    /// Field: unsigned char (UnsignedCharacter | Direct)
    [FieldOffset(48)] public CppUnsignedChar p_linear;
    /// Field: CsArray byte<br/>TypeIndex: 140371 (0x23453)
    [FieldOffset(49)] public global::MioGame.InlineArray_CppUnsignedChar_3 pad;
    #endregion
}
/// Struct type: tinyexr::FHeapCompare<br/>TypeIndex: 152744 (0x264A8)<br/>UniqueName: .?AUFHeapCompare@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 1)]
public partial struct FHeapCompare {
}
/// Struct type: tinyexr::FP16<br/>TypeIndex: 150951 (0x25DA7)<br/>UniqueName: .?ATFP16@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct FP16 {
    #region Instance Fields
    /// Field: unsigned short (UInt16Short | Direct)
    [FieldOffset(0)] public CppUInt16Short u;
    /// Field: CsStruct tinyexr__FP16__&lt;unnamed-type-s&gt;<br/>TypeIndex: 150982 (0x25DC6)
    [FieldOffset(0)] public global::MioGame.tinyexr.FP16.S s;
    #endregion
    #region Nested Types
    /// Struct type: tinyexr::FP16::&lt;unnamed-type-s&gt;<br/>TypeIndex: 150982 (0x25DC6)<br/>UniqueName: .?AU&lt;unnamed-type-s&gt;@FP16@tinyexr@@
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public partial struct S {
        #region Instance Fields
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 Mantissa;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 Exponent;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 Sign;
        #endregion
    }
    #endregion
}
/// Struct type: tinyexr::FP32<br/>TypeIndex: 150947 (0x25DA3)<br/>UniqueName: .?ATFP32@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct FP32 {
    #region Instance Fields
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(0)] public CppUInt32 u;
    /// Field: float (Float32 | Direct)
    [FieldOffset(0)] public float f;
    /// Field: CsStruct tinyexr__FP32__&lt;unnamed-type-s&gt;<br/>TypeIndex: 150961 (0x25DB1)
    [FieldOffset(0)] public global::MioGame.tinyexr.FP32.S s;
    #endregion
    #region Nested Types
    /// Struct type: tinyexr::FP32::&lt;unnamed-type-s&gt;<br/>TypeIndex: 150961 (0x25DB1)<br/>UniqueName: .?AU&lt;unnamed-type-s&gt;@FP32@tinyexr@@
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public partial struct S {
        #region Instance Fields
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 Mantissa;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 Exponent;
        /// Field: unsigned (UInt32 | Direct)
        [FieldOffset(0)] public CppUInt32 Sign;
        #endregion
    }
    #endregion
}
/// Struct type: tinyexr::HeaderInfo<br/>TypeIndex: 145916 (0x249FC)<br/>UniqueName: .?AUHeaderInfo@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 200)]
public partial struct HeaderInfo {
    #region Memory Address Access
    public static class Pointers {
        public static readonly unsafe delegate* unmanaged[Cdecl]<global::MioGame.tinyexr.HeaderInfo*, void> clear = (delegate* unmanaged[Cdecl]<global::MioGame.tinyexr.HeaderInfo*, void>)(MioGameFunctionAddress + 12870896);
    }
    #endregion
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;tinyexr__ChannelInfo,std__allocator&lt;tinyexr__ChannelInfo&gt; &gt;<br/>TypeIndex: 146091 (0x24AAB)
    [FieldOffset(0)] public global::MioGame.std.vector_tinyexr__ChannelInfo_std__allocator_tinyexr__ChannelInfo channels;
    /// Field: CsStruct std__vector&lt;_EXRAttribute,std__allocator&lt;_EXRAttribute&gt; &gt;<br/>TypeIndex: 146246 (0x24B46)
    [FieldOffset(24)] public global::MioGame.std.vector__EXRAttribute_std__allocator__EXRAttribute attributes;
    /// Field: CsStruct tinyexr__Box2iInfo<br/>TypeIndex: 145889 (0x249E1)
    [FieldOffset(48)] public global::MioGame.tinyexr.Box2iInfo data_window;
    /// Field: int (Int32 | Direct)
    [FieldOffset(64)] public CppInt32 line_order;
    /// Field: CsStruct tinyexr__Box2iInfo<br/>TypeIndex: 145889 (0x249E1)
    [FieldOffset(68)] public global::MioGame.tinyexr.Box2iInfo display_window;
    /// Field: CsArray float<br/>TypeIndex: 6808 (0x2A98)
    [FieldOffset(84)] public global::MioGame.InlineArray_float_2 screen_window_center;
    /// Field: float (Float32 | Direct)
    [FieldOffset(92)] public float screen_window_width;
    /// Field: float (Float32 | Direct)
    [FieldOffset(96)] public float pixel_aspect_ratio;
    /// Field: int (Int32 | Direct)
    [FieldOffset(100)] public CppInt32 chunk_count;
    /// Field: int (Int32 | Direct)
    [FieldOffset(104)] public CppInt32 tiled;
    /// Field: int (Int32 | Direct)
    [FieldOffset(108)] public CppInt32 tile_size_x;
    /// Field: int (Int32 | Direct)
    [FieldOffset(112)] public CppInt32 tile_size_y;
    /// Field: int (Int32 | Direct)
    [FieldOffset(116)] public CppInt32 tile_level_mode;
    /// Field: int (Int32 | Direct)
    [FieldOffset(120)] public CppInt32 tile_rounding_mode;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(124)] public CppUInt32 header_len;
    /// Field: int (Int32 | Direct)
    [FieldOffset(128)] public CppInt32 compression_type;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(136)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char name;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(168)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char type;
    #endregion
    #region Instance Methods
    public unsafe void clear() {
        fixed (global::MioGame.tinyexr.HeaderInfo* pThis = &this) {
            Pointers.clear(pThis);
        }
    }
    #endregion
}
/// Struct type: tinyexr::HufDec<br/>TypeIndex: 152967 (0x26587)<br/>UniqueName: .?AUHufDec@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct HufDec {
    #region Instance Fields
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(0)] public CppUInt32 len;
    /// Field: unsigned (UInt32 | Direct)
    [FieldOffset(0)] public CppUInt32 lit;
    /// Field: unsigned* (UInt32 | NearPointer64)
    [FieldOffset(8)] public CppUInt32* p;
    #endregion
}
/// Struct type: tinyexr::LayerChannel<br/>TypeIndex: 145842 (0x249B2)<br/>UniqueName: .?AULayerChannel@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 40)]
public partial struct LayerChannel {
    #region Instance Fields
    /// Field: unsigned __int64 (UInt64Quad | Direct)
    [FieldOffset(0)] public CppUInt64Quad index;
    /// Field: CsStruct std__basic_string&lt;char,std__char_traits&lt;char&gt;,std__allocator&lt;char&gt; &gt;<br/>TypeIndex: 3084 (0x1C0C)
    [FieldOffset(8)] public global::MioGame.std.basic_string_char_std__char_traits_char_std__allocator_char name;
    #endregion
}
/// Struct type: tinyexr::OffsetData<br/>TypeIndex: 146346 (0x24BAA)<br/>UniqueName: .?AUOffsetData@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct OffsetData {
    #region Instance Fields
    /// Field: CsStruct std__vector&lt;std__vector&lt;std__vector&lt;unsigned long long,std__allocator&lt;unsigned long long&gt; &gt;,std__allocator&lt;std__vector&lt;unsigned long long,std__allocator&lt;unsigned long long&gt; &gt; &gt; &gt;,std__allocator&lt;std__vector&lt;std__vector&lt;unsigned long long,std__allocator&lt;unsigned long long&gt; &gt;,std__allocator&lt;std__vector&lt;unsigned long long,std__allocator&lt;unsigned long long&gt; &gt; &gt; &gt; &gt; &gt;<br/>TypeIndex: 146503 (0x24C47)
    [FieldOffset(0)] public global::MioGame.std.vector_std__vector_std__vector_unsigned_long_long_std__allocator_unsigned_long_long_std__allocator_std__vector_unsigned_long_long_std__allocator_unsigned_long_long_std__allocator_std__vector_std__vector_unsigned_long_long_std__allocator_unsigned_long_long_std__allocator_std__vector_unsigned_long_long_std__allocator_unsigned_long_long offsets;
    /// Field: int (Int32 | Direct)
    [FieldOffset(24)] public CppInt32 num_x_levels;
    /// Field: int (Int32 | Direct)
    [FieldOffset(28)] public CppInt32 num_y_levels;
    #endregion
}
/// Struct type: tinyexr::PIZChannelData<br/>TypeIndex: 152282 (0x262DA)<br/>UniqueName: .?AUPIZChannelData@tinyexr@@
[StructLayout(LayoutKind.Explicit, Size = 32)]
public unsafe partial struct PIZChannelData {
    #region Instance Fields
    /// Field: unsigned short* (UInt16Short | NearPointer64)
    [FieldOffset(0)] public CppUInt16Short* start;
    /// Field: unsigned short* (UInt16Short | NearPointer64)
    [FieldOffset(8)] public CppUInt16Short* end;
    /// Field: int (Int32 | Direct)
    [FieldOffset(16)] public CppInt32 nx;
    /// Field: int (Int32 | Direct)
    [FieldOffset(20)] public CppInt32 ny;
    /// Field: int (Int32 | Direct)
    [FieldOffset(24)] public CppInt32 ys;
    /// Field: int (Int32 | Direct)
    [FieldOffset(28)] public CppInt32 size;
    #endregion
}
